# -*- coding: utf-8 -*-
"""
Created on Fri Aug 28 15:52:42 2026


/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'
from qgis.PyQt.QtCore import QCoreApplication, QVariant

from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingException,
    QgsProcessingParameterVectorLayer,
    QgsProcessingParameterRasterLayer,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterRasterDestination,
    QgsProcessingUtils,
    QgsFeature,
    QgsGeometry,
    QgsField,
    QgsPointXY
)
from qgis import processing
from osgeo import gdal, ogr
import numpy as np
import os



class RasteriserAccidents(QgsProcessingAlgorithm):
    ROADS = 'ROADS'
    ACCIDENTS = 'ACCIDENTS'
    RADIUS = 'RADIUS'
    PIXEL_SIZE = 'PIXEL_SIZE'
    OUTPUT = 'OUTPUT'
    def name(self):
        return "Calcul concentration d'accidents"

    

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Traitements'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return RasteriserAccidents()
    def initAlgorithm(self, config=None):
        # Couche du réseau routier (lignes)
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.ROADS, 'Réseau routier', [QgsProcessing.TypeVectorLine]
            )
        )
        # Points d'intérêt / Générateurs de trafic (points)
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.ACCIDENTS, 'Points des accidents', [QgsProcessing.TypeVectorPoint]
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.RADIUS, "Rayon d'attractivité (unités du CRS des accidents, ex: mètres)",
                type=QgsProcessingParameterNumber.Double,
                defaultValue=1000,
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.PIXEL_SIZE, 'Taille de pixel (unités du CRS des accidents)',
                type=QgsProcessingParameterNumber.Double,
                defaultValue=10,
            )
        )
        
        # Sink de sortie
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT, 'Réseau enrichi des accidents'
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        lignes = self.parameterAsVectorLayer(parameters, self.ROADS, context)
        accidents = self.parameterAsVectorLayer(parameters, self.ACCIDENTS, context)
        output_path = self.parameterAsOutputLayer(parameters, self.OUTPUT, context) #string
        radius = self.parameterAsDouble(parameters, self.RADIUS, context)
        pixel_size = self.parameterAsDouble(parameters, self.PIXEL_SIZE, context)
        
        for layer in (lignes, accidents):
            if layer.dataProvider().name() == 'ogr':
                layer.dataProvider().setEncoding('CP1252')
        
        feedback.pushInfo(f"Encodage réseau routier : {lignes.dataProvider().encoding()}")
        feedback.pushInfo(f"Encodage accidents : {accidents.dataProvider().encoding()}")

        #1. Densité de Kernel/carte de chaleur  pour les accidents
        feedback.pushInfo("Calcul de la densité des accidents...")
        kde_result = processing.run("qgis:heatmapkerneldensityestimation", {
            'INPUT': accidents,
            'RADIUS': radius, # Rayon de 1 km d'attractivité
            'PIXEL_SIZE': pixel_size,
            'WEIGHT_FIELD': '', # Poids selon le type de POI (ex: gare=3, commerce=1)
            'OUTPUT': QgsProcessingUtils.generateTempFilename('kde_accidents.tif')
        }, context=context, feedback=feedback)

        #2. Statistiques de zone sur les segments routiers (Attribution du score PNT)
        feedback.pushInfo("Attribution des scores d'accidents aux tronçons...")
        # Ouverture du raster
        kde_raster_path = kde_result['OUTPUT']
        src_ds = gdal.Open(kde_raster_path)
        gt = src_ds.GetGeoTransform()
        proj = src_ds.GetProjection()
        cols = src_ds.RasterXSize
        rows = src_ds.RasterYSize
        band = src_ds.GetRasterBand(1)
        nodata = band.GetNoDataValue()
        
        px_w = gt[1]
        px_h = gt[5]
        
        need_reproject = lignes.crs() != accidents.crs()
        if need_reproject:
            feedback.pushWarning(
                "Le CRS du réseau routier diffère de celui des PNT : "
                "reprojection à la volée des géométries pour le calcul des scores."
            )
        transform = None
        if need_reproject:
            from qgis.core import QgsCoordinateTransform, QgsProject
            transform = QgsCoordinateTransform(lignes.crs(), accidents.crs(), QgsProject.instance())

        
        total = lignes.featureCount()
        mem_drv = gdal.GetDriverByName('MEM')
        mask_ds = mem_drv.Create('', cols, rows, 1, gdal.GDT_Byte)
        mask_ds.SetGeoTransform(gt)
        mask_ds.SetProjection(proj)
        
        #Ajout des colonnes
        pr = lignes.dataProvider()
        lignes.startEditing()
        pr.addAttributes([
                QgsField("score_services", QVariant.Double)])
        lignes.updateFields()
        
        idx = lignes.fields().lookupField('score_services')
        mem_ogr_drv = ogr.GetDriverByName('Memory')

        for current, feature in enumerate(lignes.getFeatures()):
            if feedback.isCanceled():
                break
 
            geom = feature.geometry()
            if transform is not None:
                geom = QgsGeometry(geom)
                geom.transform(transform)
 
            bbox = geom.boundingBox()
            if bbox.isEmpty():
                pr.changeAttributeValues({feature.id(): {idx: 0.0}})
                continue
 
            # Fenêtre pixel correspondant à la bbox du tronçon (+1 pixel de
            # marge) au lieu de recalculer un masque sur tout le raster.
            col_min = max(0, int((bbox.xMinimum() - gt[0]) / px_w) - 1)
            col_max = min(cols, int((bbox.xMaximum() - gt[0]) / px_w) + 2)
            row_min = max(0, int((bbox.yMaximum() - gt[3]) / px_h) - 1)
            row_max = min(rows, int((bbox.yMinimum() - gt[3]) / px_h) + 2)
 
            win_cols = col_max - col_min
            win_rows = row_max - row_min
            if win_cols <= 0 or win_rows <= 0:
                pr.changeAttributeValues({feature.id(): {idx: 0.0}})
                continue
 
            sub_gt = (
                gt[0] + col_min * px_w, px_w, 0,
                gt[3] + row_min * px_h, 0, px_h,
            )
 
            mem_ogr_ds = mem_ogr_drv.CreateDataSource('mem')
            mem_ogr_layer = mem_ogr_ds.CreateLayer('line', geom_type=ogr.wkbLineString)
            ogr_feat = ogr.Feature(mem_ogr_layer.GetLayerDefn())
            ogr_feat.SetGeometry(ogr.CreateGeometryFromWkt(geom.asWkt()))
            mem_ogr_layer.CreateFeature(ogr_feat)
 
            mask_ds = mem_drv.Create('', win_cols, win_rows, 1, gdal.GDT_Byte)
            mask_ds.SetGeoTransform(sub_gt)
            mask_ds.SetProjection(proj)
            gdal.RasterizeLayer(
                mask_ds, [1], mem_ogr_layer,
                burn_values=[1],
                options=['ALL_TOUCHED=TRUE'],
            )
            mask_array = mask_ds.GetRasterBand(1).ReadAsArray()
            src_window = band.ReadAsArray(col_min, row_min, win_cols, win_rows).astype(float)
 
            pixels_values = src_window[mask_array == 1]
            if nodata is not None:
                pixels_values = pixels_values[pixels_values != nodata]
 
            score = float(pixels_values.mean()) if pixels_values.size > 0 else 0.0
            pr.changeAttributeValues({feature.id(): {idx: score}})
 
            # Libération explicite des objets GDAL/OGR temporaires
            mask_ds = None
            mem_ogr_ds = None
 
            if total > 0:
                feedback.setProgress(int(current / total * 100))
 
        lignes.commitChanges()


        
        
        
       
        raster = processing.run("gdal:rasterize", 
                   {'INPUT': lignes,
                    'FIELD':'score_services',
                    'BURN':0,
                    'USE_Z':False,
                    'UNITS':1,
                    'WIDTH':10,'HEIGHT':10,
                    'EXTENT':None,'NODATA':0,
                    'CREATION_OPTIONS':None,
                    'DATA_TYPE':5,'INIT':None,
                    'INVERT':False,'EXTRA':'',
                    'OUTPUT': QgsProcessingUtils.generateTempFilename(
                        'score_services_rasterized.tif', context)}
                   )['OUTPUT']
        
        ds = gdal.Open(raster) if isinstance(raster, str) else raster
        if ds is None:
            raise RuntimeError(f"Impossible d'ouvrir le raster généré : {raster}")
        band = ds.GetRasterBand(1)
        arr = ds.GetRasterBand(1).ReadAsArray().astype(float)
        feedback.pushInfo(f"Dimensions : {ds.RasterXSize} x {ds.RasterYSize} pixels")
        feedback.pushInfo(f"NoData : {band.GetNoDataValue()}")
        feedback.pushInfo(f"Min : {np.nanmin(arr)}, Max : {np.nanmax(arr)}, Moyenne : {np.nanmean(arr):.2f}")
        feedback.pushInfo(f"Valeurs uniques (10 premières) : {np.unique(arr)[:10]}")
        feedback.pushInfo(f"% de pixels à 0 : {(arr == 0).sum() / arr.size * 100:.1f}%")
        
        nodata = band.GetNoDataValue()
        if nodata is not None:
            valid_mask = arr != nodata
        else:
            valid_mask = np.ones(arr.shape, dtype=bool)

        if not valid_mask.any():
            raise QgsProcessingException(
                "Le raster ne contient aucune valeur valide (tout est NoData)."
            )

        r_min = float(arr[valid_mask].min())
        r_max = float(arr[valid_mask].max())
        feedback.pushInfo(f"Densité min={r_min}, max={r_max} (NoData exclu)")

        if r_max == r_min:
            feedback.pushWarning("Toutes les valeurs sont identiques, la normalisation est ignorée.")
            norm = np.zeros_like(arr)
        else:
            norm = np.where(
                valid_mask,
                (arr - r_min) / (r_max - r_min) * 100,
                nodata if nodata is not None else -9999
            )

       
        driver = gdal.GetDriverByName('GTiff')
        out_ds = driver.Create(
            output_path, ds.RasterXSize, ds.RasterYSize, 1, gdal.GDT_Float32
        )
        out_ds.SetGeoTransform(ds.GetGeoTransform())
        out_ds.SetProjection(ds.GetProjection())
        out_band = out_ds.GetRasterBand(1)
        if nodata is not None:
            out_band.SetNoDataValue(nodata)
        out_band.WriteArray(norm.astype(np.float32))
        out_band.FlushCache()
        out_ds = None
        ds = None
        
        return {self.OUTPUT: output_path}

    