# -*- coding: utf-8 -*-
"""
Created on Fri Aug 28 15:52:42 2026


/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'
from qgis.PyQt.QtCore import QCoreApplication, QVariant

from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingParameterVectorLayer,
    QgsProcessingParameterRasterLayer,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterRasterDestination,
    QgsProcessingUtils,
    QgsFeature,
    QgsGeometry,
    QgsField,
    QgsPointXY
)
from qgis import processing
from osgeo import gdal, ogr
import numpy as np
import os



class RasteriserAccidents(QgsProcessingAlgorithm):
    ROADS = 'ROADS'
    ACCIDENTS = 'ACCIDENTS'
    OUTPUT = 'OUTPUT'
    def name(self):
        return "Calcul concentration d'accidents"

    

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Traitements'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return RasteriserAccidents()
    def initAlgorithm(self, config=None):
        # Couche du réseau routier (lignes)
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.ROADS, 'Réseau routier', [QgsProcessing.TypeVectorLine]
            )
        )
        # Points d'intérêt / Générateurs de trafic (points)
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.ACCIDENTS, 'Points des accidents', [QgsProcessing.TypeVectorPoint]
            )
        )
        
        # Sink de sortie
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT, 'Réseau enrichi de la demande'
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        lignes = self.parameterAsVectorLayer(parameters, self.ROADS, context)
        pois = self.parameterAsVectorLayer(parameters, self.ACCIDENTS, context)
        output_raster = self.parameterAsOutputLayer(parameters, self.OUTPUT, context)
        
        for layer in (lignes, pois):
            if layer.dataProvider().name() == 'ogr':
                layer.dataProvider().setEncoding('CP1252')
        
        feedback.pushInfo(f"Encodage réseau routier : {lignes.dataProvider().encoding()}")
        feedback.pushInfo(f"Encodage accidents : {pois.dataProvider().encoding()}")

        #1. Densité de Kernel/carte de chaleur  pour les accidents
        feedback.pushInfo("Calcul de la densité des accidents...")
        kde_result = processing.run("qgis:heatmapkerneldensityestimation", {
            'INPUT': pois,
            'RADIUS': 1000, # Rayon de 1 km d'attractivité
            'PIXEL_SIZE': 10,
            'WEIGHT_FIELD': '', # Poids selon le type de POI (ex: gare=3, commerce=1)
            'OUTPUT': QgsProcessingUtils.generateTempFilename('kde_accidents.tif')
        }, context=context, feedback=feedback)

        #2. Statistiques de zone sur les segments routiers (Attribution du score PNT)
        feedback.pushInfo("Attribution des scores d'attractivité aux tronçons...")
        kde_raster_path = kde_result['OUTPUT']
        pr = lignes.dataProvider()
        lignes.startEditing()
        pr.addAttributes([
                QgsField("join_fid", QVariant.LongLong),
                QgsField("score_services", QVariant.Double)])
        lignes.updateFields()
        
        idx_join = lignes.fields().lookupField('join_fid')
        idx = lignes.fields().lookupField('score_services')
        
        join_updates = {f.id(): {idx_join: f.id()} for f in lignes.getFeatures()}
        pr.changeAttributeValues(join_updates)
        lignes.commitChanges()


        buffered = processing.run("native:buffer", {
            'INPUT': lignes,
            'DISTANCE': 5,  
            'SEGMENTS': 5,
            'DISSOLVE': False,
            'OUTPUT': 'memory:'
        }, context=context, feedback=feedback)['OUTPUT']
        
        print("Buffer fait!")
        zonal = processing.run("native:zonalstatisticsfb", {
            'INPUT': buffered,
            'INPUT_RASTER': kde_raster_path,
            'RASTER_BAND': 1,
            'COLUMN_PREFIX': 'score_',
            'STATISTICS': [2],  #Moyenne
            'OUTPUT': 'memory:'
        }, context=context, feedback=feedback)['OUTPUT']
        print("Stats zonales faites!")

        
        
        lignes.startEditing()
        scores = {f['join_fid']: f['score_mean'] for f in zonal.getFeatures()}
        

        updates = {f.id(): {idx: (scores.get(f['join_fid']) if scores.get(f['join_fid']) is not None else 0.0)}
            for f in lignes.getFeatures()}
        pr.changeAttributeValues(updates)  # une seule écriture groupée au lieu d'une par entité
        lignes.commitChanges()
       
        raster = processing.run("gdal:rasterize", 
                   {'INPUT': lignes,
                    'FIELD':'score_services',
                    'BURN':0,
                    'USE_Z':False,
                    'UNITS':1,
                    'WIDTH':10,'HEIGHT':10,
                    'EXTENT':None,'NODATA':0,
                    'CREATION_OPTIONS':None,
                    'DATA_TYPE':5,'INIT':None,
                    'INVERT':False,'EXTRA':'',
                    'OUTPUT': QgsProcessingUtils.generateTempFilename(
                        'score_services_rasterized.tif', context)}
                   )['OUTPUT']
        
        ds = gdal.Open(raster) if isinstance(raster, str) else raster
        arr = ds.GetRasterBand(1).ReadAsArray().astype(float)
        r_min = float(np.nanmin(arr))
        r_max = float(np.nanmax(arr))
        feedback.pushInfo(f"score_services min={r_min}, max={r_max}")
        if r_max == r_min:
            feedback.pushWarning("Toutes les valeurs sont identiques, la normalisation est ignorée.")
            formula = "A*0"  # ou une autre valeur par défaut
        else:
            formula = f"((A - {r_min}) / ({r_max} - {r_min})) * 100"

        calcul = processing.run("gdal:rastercalculator", 
                       {'INPUT_A':raster,
                        'BAND_A':1,
                        'INPUT_B':None,'BAND_B':None,
                        'INPUT_C':None,'BAND_C':None,
                        'INPUT_D':None,'BAND_D':None,
                        'INPUT_E':None,'BAND_E':None,
                        'INPUT_F':None,'BAND_F':None,
                        'FORMULA':formula,
                        'NO_DATA':None,
                        'EXTENT_OPT':0,'PROJWIN':None,
                        'RTYPE':5,'CREATION_OPTIONS':None,
                        'EXTRA':'',
                        'OUTPUT':output_raster})
        
        return {self.OUTPUT: calcul['OUTPUT']}

    