# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-08-12'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterString,
                       QgsProcessingParameterEnum, 
                       QgsProcessingParameterNumber,
                       QgsField,
                       QgsFeature)

from qgis.analysis import (
    QgsVectorLayerDirector,
    QgsNetworkDistanceStrategy,
    QgsNetworkSpeedStrategy,
    QgsGraphBuilder,
    QgsGraphAnalyzer
)
from qgis import processing


class AjoutTrafic(QgsProcessingAlgorithm):
    """
    Algorithme pour ajouter l'information de trafic depuis une couche de points à une couche de
    noeuds.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    RESEAU = 'RESEAU'
    MAXDIST = "MAXDIST"
    SPEED_FIELD = 'SPEED_FIELD'
    DIRECTION_FIELD = 'DIRECTION_FIELD'
    TRAFIC_PL = 'TRAFIC_PL'

    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Ajouter le trafic'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Formatage'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return AjoutTrafic()
    
    def initAlgorithm(self, config):
        

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Couche de trafic (point)'),
                [QgsProcessing.SourceType.TypeVectorPoint]
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.RESEAU,
                self.tr('Couche de réseau (lignes)'),
                [QgsProcessing.SourceType.TypeVectorLine]
            )
        )
        self.addParameter(QgsProcessingParameterField(self.DIRECTION_FIELD, 
                                                      self.tr("Colonne nom"),
                                                      parentLayerParameterName=self.RESEAU,
                                                      optional= False))
        
        self.addParameter(QgsProcessingParameterField(self.SPEED_FIELD, 
                                                      self.tr("Colonne trafic"), 
                                                      parentLayerParameterName=self.INPUT,
                                                      optional=False))
        self.addParameter(QgsProcessingParameterField(self.TRAFIC_PL, 
                                                       self.tr("Colonne trafic poids lourds (si existe)"), 
                                                       parentLayerParameterName=self.INPUT,
                                                       optional=True))
       
        
        self.addParameter(QgsProcessingParameterNumber(self.MAXDIST, self.tr("Distance maximum entre les entités"), defaultValue=0.0))

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        reseau = self.parameterAsSource(parameters, self.RESEAU, context)
        
        max_dist  = self.parameterAsDouble(parameters, self.DISTANCE_MAX, context)  # tolérance en unités de la couche
        field_trafic = self.parameterAsString(parameters, self.SPEED_FIELD, context)
        field_nom = self.parameterAsString(parameters, self.DIRECTION_FIELD, context)
        field_pl = self.parameterAsString(parameters, self.DEFAULT_SPEED, context)

        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, source.fields(), source.wkbType(), source.sourceCrs())
        
        
        source.startEditing()
        source.dataProvider().addAttributes([QgsField('position_key', QVariant.String)])
        source.updateFields()
        idx_key = source.fields().indexOf('position_key')
    
    
        precision=6
        groups = {}
        for feat in source.getFeatures():
            geom = feat.geometry()
            pt = geom.asPoint()  
            key = f"{round(pt.x(), precision)}_{round(pt.y(), precision)}"
            source.changeAttributeValue(feat.id(), idx_key, key)
            groups.setdefault(key, []).append(feat)
        
            
        source.commitChanges()
        merged_features = []
        for key, feats in groups.items():
            values = [f[field_trafic] for f in feats if f[field_trafic] not in (None,)]
            mean_val = sum(values) / len(values) if values else None
     
            new_feat = QgsFeature(feats[0].fields())
            new_feat.setGeometry(feats[0].geometry())
            new_feat.setAttributes(feats[0].attributes())
            new_feat.setAttribute(field_trafic, mean_val)
            merged_features.append(new_feat)
        
        cpt_aggre = processing.run("native:aggregate", 
                       {'INPUT': source,
                        'GROUP_BY':'position_key',
                        'AGGREGATES':[
                            {
                            'aggregate': 'first_value',
                            'delimiter': ',',
                            'input': 'position_key',
                            'length': 0,
                            'name': 'position_key',
                            'precision': 0,
                            'type': 10
                            },  
                            {'aggregate': 'first_value',
                                       'delimiter': ',',
                                       'input': '"AXE"',
                                       'length': 30,
                                       'name': 'AXE','precision': 0,
                                       'sub_type': 0,'type': 10,'type_name': 'text'},
                                      {'aggregate': 'first_value',
                                       'delimiter': ',','input': '"TYPE_COMPT"',
                                       'length': 20,'name': 'TYPE_COMPT',
                                       'precision': 0,'sub_type': 0,'type': 10,'type_name': 'text'},
                                      {'aggregate': 'sum','delimiter': ',',
                                       'input': '"TRAFIC_VL"','length': 11,'name': 'TRAFIC_VL',
                                       'precision': 0,'sub_type': 0,'type': 4,
                                       'type_name': 'int8'},
                                      {'aggregate': 'maximum','delimiter': ',',
                                       'input': '"ANNEE"','length': 11,'name': 'ANNEE',
                                       'precision': 0,'sub_type': 0,'type': 4,
                                       'type_name': 'int8'},
                                      {'aggregate': 'mean','delimiter': ',',
                                       'input': field_trafic,'length': 11,'name': field_trafic,
                                       'precision': 0,'sub_type': 0,'type': 4,
                                       'type_name': 'int8'},
                                      {'aggregate': 'sum','delimiter': ',',
                                       'input': '"PART_PL"','length': 8,'name': 'PART_PL',
                                       'precision': 2,'sub_type': 0,'type': 6,
                                       'type_name': 'double precision'},
                                      {'aggregate': 'sum','delimiter': ',',
                                       'input': '"TRAFIC_PL"','length': 11,'name': 'TRAFIC_PL',
                                       'precision': 0,'sub_type': 0,'type': 4,
                                       'type_name': 'int8'},
                                      {'aggregate': 'concatenate','delimiter': ',',
                                       'input': '"CODE"','length': 25,'name': 'CODE',
                                       'precision': 0,'sub_type': 0,'type': 10,
                                       'type_name': 'text'}],
                        'OUTPUT':'memory:compteurs_moyennes'
                        },  context=context, feedback=feedback)['OUTPUT']
        

        result = processing.run("native:joinbynearest", 
                       {'INPUT':reseau,'INPUT_2': source,
                        'FIELDS_TO_COPY':[],
                        'DISCARD_NONMATCHING':False,
                        'PREFIX':'','NEIGHBORS':1,
                        'MAX_DISTANCE':max_dist,'OUTPUT': 'memory'}
                       , context=context, feedback=feedback)['OUTPUT']
        
        idx_trafic = result.fields().indexOf(field_trafic)
        idx_nom = result.fields().indexOf(field_nom)
    
        feats = {f.id(): f for f in result.getFeatures()}
    
        def endpoints(fid):
            geom = feats[fid].geometry()
            line = geom.asMultiPolyline()[0] if geom.isMultipart() else geom.asPolyline()
            return (line[0], line[-1])
    
        # index des noeuds : {coord arrondie: [fid, fid, ...]}
        vertex_index = {}
        for fid in feats.keys():
            for pt in endpoints(fid):
                key = (round(pt.x(), precision), round(pt.y(), precision))
                vertex_index.setdefault(key, []).append(fid)
    
        queue = [fid for fid, f in feats.items() if f[field_trafic] not in (None, 'NULL')]
    
        result.startEditing()
    
        while queue:
            current_fid = queue.pop(0)
            current_val = feats[current_fid][field_trafic]
            current_nom = feats[current_fid][field_nom]
    
            for pt in endpoints(current_fid):
                key = (round(pt.x(), precision), round(pt.y(), precision))
                neighbors = vertex_index.get(key, [])
    
                if len(neighbors) > 2:
                    continue  #vraie intersection -> on ne propage pas à travers ce noeud
    
                for n_fid in neighbors:
                    if n_fid == current_fid:
                        continue
                    n_feat = feats[n_fid]
    
                    if n_feat[field_trafic] not in (None, 'NULL'):
                        continue  # déjà une valeur, on ne l'écrase pas
                    if n_feat[field_nom] != current_nom:
                        continue  # nom différent donc pas la même route
    
                    result.changeAttributeValue(n_fid, idx_trafic, current_val)
                    n_feat.setAttribute(idx_trafic, current_val)  
                    queue.append(n_fid)
    
        result.commitChanges()
        
        
        
        
        
        (sink, dest_id) = self.parameterAsSink(
        parameters, self.OUTPUT, context,
        result.fields(), result.wkbType(), result.sourceCrs()
        )
        for feat in result.getFeatures():
            sink.addFeature(feat, QgsFeatureSink.FastInsert)
        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.OUTPUT: dest_id}

