"""
/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-08-12'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureRequest,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterString,
                       QgsProcessingParameterEnum, 
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFile,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsGeometry,
                       QgsFields,
                       QgsField)

from qgis.analysis import (
    QgsVectorLayerDirector,
    QgsNetworkDistanceStrategy,
    QgsNetworkSpeedStrategy,
    QgsGraphBuilder,
    QgsGraphAnalyzer
)
from qgis import processing

from collections import OrderedDict, defaultdict
from scipy.spatial import cKDTree
import pandas as pd

class AnalyseExistant(QgsProcessingAlgorithm):
    """
    Algorithme pour trouver où sont les aménagements cyclables déjà en place
    et où il y a discontinuité
    """
    RESEAU = 'RESEAU'
    COLAME = 'COLAME'
    
    
    OUTPUT = 'OUTPUT'
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Analyse discontinuité des aménagements cyclables'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Traitements'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return AnalyseExistant()
    
    def initAlgorithm(self, config):
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.RESEAU,
                self.tr('Réseau'),
                [QgsProcessing.SourceType.TypeVectorLine]
            )
        )
        
        self.addParameter(QgsProcessingParameterField(self.COLAME, 
                                                      self.tr("Colonne direction"),
                                                      parentLayerParameterName=self.RESEAU,
                                                      optional= False,
                                                      allowMultiple = True))
        
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        reseau = self.parameterAsSource(parameters, self.RESEAU, context)
        col_ame = self.parameterAsStrings(parameters, self.COLAME, context)

        
        
        # 1.Extraire les routes avec aménagements
        expr = f'"{col_ame}" IS NOT NULL'
        request = QgsFeatureRequest().setFilterExpression(expr)
        
        velo = reseau.materialize(request)
        
        # 2.Trouver les trous
        # a.Calculer les composantes connexes
        result_pts = processing.run(
            "grass:v.net.components", 
            {'input':velo,
             'points':None,
             'threshold':50,
             'method':0,
             'arc_column':'',
             'arc_backward_column':'',
             'node_column':'','-a':True,
             'output':'memory:ligne',
             'output_point':'memory:points',
             'GRASS_REGION_PARAMETER':None,
             'GRASS_SNAP_TOLERANCE_PARAMETER':-1,
             'GRASS_MIN_AREA_PARAMETER':0.0001,
             'GRASS_OUTPUT_TYPE_PARAMETER':0,'GRASS_VECTOR_DSCO':'',
             'GRASS_VECTOR_LCO':'','GRASS_VECTOR_EXPORT_NOCAT':False})
        
        velo_lines = result_pts['output']
        velo_nodes = result_pts['output_point']
        
        # b.Trouver les routes connectant différentes composantes connexes
        
        
        expr_sans = f'"{col_ame}" IS NULL'
        request_sans = QgsFeatureRequest().setFilterExpression(expr_sans)
        sans_ame = reseau.materialize(request_sans)
        
        # On crée un 'id' car l'algo extraxtspecificvertices efface les fid
        sans_ame_id = sans_ame.materialize(QgsFeatureRequest())  # copie
        sans_ame_id.startEditing()
        sans_ame_id.addAttribute(QgsField('seg_id', QVariant.Int))
        sans_ame_id.updateFields()
        idx = sans_ame_id.fields().indexOf('seg_id')
        for f in sans_ame_id.getFeatures():
            sans_ame_id.changeAttributeValue(f.id(), idx, f.id())
        sans_ame_id.commitChanges()
        
        extremites = processing.run(
        "native:extractspecificvertices",
        {'INPUT': sans_ame_id,
         'VERTICES': '0,-1',
         'OUTPUT': 'memory:'})['OUTPUT']
        
        #Jointure
        join = processing.run(
        "native:joinbynearest",
        {'INPUT': extremites,
         'INPUT_2': velo_nodes,
         'FIELDS_TO_COPY': ['cluster'],
         'DISCARD_NONMATCHING': False,
         'PREFIX': 'velo_',
         'NEIGHBORS': 1,
         'MAX_DISTANCE': 50,
         'OUTPUT': 'memory:'})['OUTPUT']
        
        clusters_par_segment = defaultdict(dict)  # {feature_id: {vertex_index: cluster}}
        
        for f in join.getFeatures():
            fid_origine = f['seg_id']   
            vidx = f['vertex_index']
            cluster = f['velo_compo']
            clusters_par_segment[fid_origine][vidx] = cluster

        candidats_ids = []
        for fid, d in clusters_par_segment.items():
            c0 = d.get(0)
            c1 = d.get(-1)
            if c0 is not None and c1 is not None and c0 != c1:
                candidats_ids.append(fid)
        expr_candidats = f'"seg_id" IN ({",".join(map(str, candidats_ids))})'  # adapter le nom du champ ID
        request_candidats = QgsFeatureRequest().setFilterExpression(expr_candidats)
        chainons_manquants = sans_ame.materialize(request_candidats)
        
        
        
        feat = next(chainons_manquants.getFeatures(QgsFeatureRequest().setFilterFid(1)))
        fields = feat.fields()
        (sink_traffic, dest_id) = self.parameterAsSink(
        parameters, self.OUTPUT, context,
        fields, QgsWkbTypes.LineString, reseau.crs()
        )
        
        for feat in chainons_manquants.getFeatures():
            sink_traffic.addFeature(feat, QgsFeatureSink.FastInsert)

        return {self.OUTPUT: dest_id}
    
