# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'
from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (
    QgsProcessing,
    QgsRasterLayer,
    QgsFeatureRequest,
    QgsProcessingAlgorithm,
    QgsProcessingParameterVectorLayer,
    QgsProcessingParameterRasterLayer,
    QgsProcessingParameterBand,
    QgsProcessingParameterNumber,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterRasterDestination,
    QgsFeature,
    QgsFeatureSink,
    QgsField,
    QgsFields,
    QgsWkbTypes,
    QgsCoordinateTransform,
    QgsProject,
    QgsDistanceArea,
    QgsPointXY,
)
from qgis import processing
from osgeo import gdal
import numpy as np

class AddGradeAlgorithm(QgsProcessingAlgorithm):
 
    INPUT = "INPUT"
    DEM = "DEM"
    BAND = "BAND"
    TOLERANCE = "TOLERANCE"
    AS_PERCENT = "AS_PERCENT"
    VAE = "VAE"
    OUTPUT = "OUTPUT"
 
    def tr(self, string):
        return QCoreApplication.translate("AddGradeAlgorithm", string)
 
    def createInstance(self):
        return AddGradeAlgorithm()
 
    def name(self):
        return "road_network_grades"
 
    def displayName(self):
        return self.tr("Ajouter la pente aux lignes d'un réseau")
 
    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Traitements'
 
    def shortHelpString(self):
        return self.tr(
            "Calcule la pente de chaque tronçon (arête) d'un réseau linéaire "
            "à partir d'un MNT, en garantissant que deux arêtes partageant un "
            "même nœud utilisent exactement la même altitude à ce nœud."
            "Ces tronçons sont ensuite rasterisés."
        )
 
    def initAlgorithm(self, config=None):
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT,
                self.tr("Réseau routier (lignes)"),
                types=[QgsProcessing.TypeVectorLine],
            )
        )
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.DEM, self.tr("MNT (raster d'altitude)")
            )
        )
        self.addParameter(
            QgsProcessingParameterBand(
                self.BAND, self.tr("Bande du MNT"), 1, self.DEM
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.TOLERANCE,
                self.tr(
                    "Tolérance de fusion des nœuds (unités de la couche, "
                    "ex: 0.01 = 1cm si projeté en mètres)"
                ),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=0.01,
                minValue=0.0,
            )
        )
        self.addParameter(
            QgsProcessingParameterBoolean(
                self.AS_PERCENT,
                self.tr("Exprimer la pente en pourcentage (sinon ratio)"),
                defaultValue=True,
            )
        )
        
        self.addParameter(
            QgsProcessingParameterBoolean(
                self.VAE,
                self.tr("VAE"),
                defaultValue=False,
            )
        )
        self.addParameter(
            QgsProcessingParameterRasterDestination(self.OUTPUT, self.tr("Raster de pente"))
        )
 
    def _endpoints(self, geom):
        """Retourne (premier_sommet, dernier_sommet) en gérant simple/multi lignes."""
        if geom.isMultipart():
            parts = geom.asMultiPolyline()
            parts = [p for p in parts if p]
            if not parts:
                return None, None
            first_pt = parts[0][0]
            last_pt = parts[-1][-1]
        else:
            line = geom.asPolyline()
            if not line:
                return None, None
            first_pt = line[0]
            last_pt = line[-1]
        return QgsPointXY(first_pt), QgsPointXY(last_pt)
 
    def processAlgorithm(self, parameters, context, feedback):
        source = self.parameterAsVectorLayer(parameters, self.INPUT, context)
        dem = self.parameterAsRasterLayer(parameters, self.DEM, context)
        band = self.parameterAsInt(parameters, self.BAND, context)
        tol = self.parameterAsDouble(parameters, self.TOLERANCE, context)
        as_percent = self.parameterAsBool(parameters, self.AS_PERCENT, context)
        vae = self.parameterAsBool(parameters, self.VAE, context)

 
        if tol <= 0:
            tol = 0.01  # évite une division par zéro dans l'arrondi
 
        #Vérification de la cohérence des crs
        transform = None
        if source.crs() != dem.crs():
            transform = QgsCoordinateTransform(
                source.crs(), dem.crs(), QgsProject.instance()
            )
 
        # Pour la longueur "vraie" (ellipsoïdale si CRS géographique)
        distance_area = QgsDistanceArea()
        distance_area.setSourceCrs(source.crs(), QgsProject.instance().transformContext())
        distance_area.setEllipsoid(QgsProject.instance().ellipsoid())
        
        densified = processing.run("native:densifygeometriesgivenaninterval", {
                "INPUT": source,
                "INTERVAL": 5.0,
                "OUTPUT": "memory:",
            })["OUTPUT"]
        
 
        provider = dem.dataProvider()
        
        #----------------test---------------------------------------
        feature = next(densified.getFeatures())
        vertices = feature.geometry().asPolyline()
        
        profile = []
        cumulative = 0.0
        previous = None
        extent = feature.geometry().boundingBox()
        extent.grow(dem.rasterUnitsPerPixelX() * 2)
        
        width = int(extent.width() / dem.rasterUnitsPerPixelX())
        height = int(extent.height() / dem.rasterUnitsPerPixelY())
        block = provider.block(1, extent, width, height)
        
        def value_at(point):
            col = int((point.x() - extent.xMinimum()) / dem.rasterUnitsPerPixelX())
            row = int((extent.yMaximum() - point.y()) / dem.rasterUnitsPerPixelY())
            if 0 <= col < width and 0 <= row < height:
                return block.value(row, col)
            return None
        
        for point in vertices:
            value, ok = provider.sample(QgsPointXY(point), 1)
            if previous is not None:
                cumulative += previous.distance(point)
            previous = point
            if ok and value != nodata:
                profile.append((cumulative, value))
        
        rows = []
        for index, (chainage, height) in enumerate(profile):
            if index == 0:
                gradient = 0.0
            else:
                run = chainage - profile[index - 1][0]
                rise = height - profile[index - 1][1]
                gradient = (rise / run * 100.0) if run else 0.0
            rows.append({"chainage": chainage, "height": height, "gradient_pct": gradient})
        
        climb = sum(r["height"] - p["height"] for p, r in zip(rows, rows[1:]) if r["height"] > p["height"])
        descent = sum(p["height"] - r["height"] for p, r in zip(rows, rows[1:]) if r["height"] < p["height"])
        print(f"total climb {climb:.1f} m, total descent {descent:.1f} m, "
              f"steepest {max(abs(r['gradient_pct']) for r in rows):.1f}%")
        #--------------------------------------------------------------------
 
        # ---- Passe 1 : identifier les nœuds uniques (snap par grille) ----
        feedback.pushInfo("Étape 1/3 : identification des nœuds du réseau...")
        node_repr_point = {}  # clé de grille -> point représentatif (CRS du MNT)
        features = list(source.getFeatures())
        total = len(features) or 1
 
        for i, feat in enumerate(features):
            if feedback.isCanceled():
                return {}
            geom = feat.geometry()
            if geom is None or geom.isEmpty():
                continue
            p_start, p_end = self._endpoints(geom)
            if p_start is None:
                continue
            for pt in (p_start, p_end):
                pt_dem = transform.transform(pt) if transform else pt
                key = (round(pt_dem.x() / tol), round(pt_dem.y() / tol))
                if key not in node_repr_point:
                    node_repr_point[key] = pt_dem
            feedback.setProgress(int(30 * i / total))
 
        # ---- échantillonner le MNT une seule fois par nœud ----
        feedback.pushInfo(
            f"Étape 2/3 : échantillonnage du MNT sur {len(node_repr_point)} nœuds uniques..."
        )
        node_elev = {}
        n_nodes = len(node_repr_point) or 1
        for j, (key, pt_dem) in enumerate(node_repr_point.items()):
            if feedback.isCanceled():
                return {}
            val, ok = provider.sample(pt_dem, band)
            node_elev[key] = val if ok and val is not None else None
            feedback.setProgress(30 + int(30 * j / n_nodes))
        
 
        # ---- Préparation des champs de sortie ----
        lignes = source.materialize(QgsFeatureRequest())

        pr = lignes.dataProvider()
        lignes.startEditing()
        
        #out_fields = QgsFields(source.fields())
        for fname, ftype in (
            ("elev_start", QVariant.Double),
            ("elev_end", QVariant.Double),
            #("length_m", QVariant.Double),
            ("grade", QVariant.Double),
            ("grade_abs", QVariant.Double),
        ):
            pr.addAttributes([QgsField(fname, ftype)])
        
        lignes.updateFields()
        idx_1 = lignes.fields().lookupField('elev_start')
        idx_2 = lignes.fields().lookupField('elev_end')
        idx_3 = lignes.fields().lookupField('grade')    
        idx_4 = lignes.fields().lookupField('grade_abs')    

 
        # ---- calcul de la pente par arête ----
        feedback.pushInfo("Étape 3/3 : calcul de la pente par tronçon...")
        n_missing_dem = 0
        for i, feat in enumerate(features):
            if feedback.isCanceled():
                return {}
            geom = feat.geometry()
            elev_start = elev_end = length_m = grade = grade_abs = None
            if geom is not None and not geom.isEmpty():
                p_start, p_end = self._endpoints(geom)
                if p_start is not None:
                    pt_start_dem = transform.transform(p_start) if transform else p_start
                    pt_end_dem = transform.transform(p_end) if transform else p_end
                    key_start = (round(pt_start_dem.x() / tol), round(pt_start_dem.y() / tol))
                    key_end = (round(pt_end_dem.x() / tol), round(pt_end_dem.y() / tol))
                    elev_start = node_elev.get(key_start)
                    elev_end = node_elev.get(key_end)
 
                    try:
                        length_m = distance_area.measureLength(geom)
                    except Exception:
                        length_m = geom.length()
 
                    if elev_start is None or elev_end is None:
                        n_missing_dem += 1
                    elif length_m and length_m > 0:
                        grade = (elev_end - elev_start) / length_m
                        if as_percent:
                            grade *= 100.0
                        print(grade)
                        grade_abs = abs(grade)
 
            
            pr.changeAttributeValues({feat.id():{idx_1: elev_start,
                                                    idx_2: elev_end,
                                                    idx_3: grade,
                                                    idx_4: grade_abs}})
            
            feedback.setProgress(60 + int(40 * i / total))
 
        if n_missing_dem:
            feedback.pushWarning(
                f"{n_missing_dem} tronçon(s) sans altitude valide "
                "(hors emprise du MNT ou NoData)."
            )
            
        raster_path = processing.run("gdal:rasterize", 
                       {'INPUT': lignes,
                        'FIELD':'grade',
                        'BURN':0,
                        'USE_Z':False,
                        'UNITS':1,
                        'WIDTH':10,'HEIGHT':10,
                        'EXTENT':None,'NODATA':-9999,
                        'CREATION_OPTIONS':None,
                        'DATA_TYPE':5,'INIT':-9999,
                        'INVERT':False,'EXTRA':'',
                        'OUTPUT':QgsProcessing.TEMPORARY_OUTPUT},
                       context=context,
                       feedback=feedback,)['OUTPUT']
        
        raster = QgsRasterLayer(raster_path, 'grade_raster')
        if not raster.isValid():
            raise Exception(
                f"Le raster de pente intermédiaire n'a pas pu être chargé "
                f"depuis {raster_path}."
            )
        array=raster.as_numpy()
        ds = gdal.Open(raster_path) if isinstance(raster_path, str) else raster
        if ds is None:
            raise RuntimeError(f"Impossible d'ouvrir le raster généré : {raster}")
        band = ds.GetRasterBand(1)
        
        feedback.pushInfo(f"Dimensions : {raster.rasterUnitsPerPixelX} x {raster.rasterUnitsPerPixelY} pixels")
        feedback.pushInfo(f"NoData : {band.GetNoDataValue()}")
        feedback.pushInfo(f"Min : {np.nanmin(array)}, Max : {np.nanmax(array)}, Moyenne : {np.nanmean(array):.2f}")
        feedback.pushInfo(f"Valeurs uniques (10 premières) : {np.unique(array)[:10]}")
        feedback.pushInfo(f"% de pixels à 0 : {(array == 0).sum() / array.size * 100:.1f}%")

        if vae:
            formula = f'if( "{raster.name()}@1" = -9999, -9999, if("{raster.name()}@1"<5,100, if("{raster.name()}@1">10,0,((10-"{raster.name()}@1") / (10-5)*100))))'
            
        
    

            result = processing.run(
                "native:rastercalc", 
                {'LAYERS':[raster],
                 'EXPRESSION':formula,
                 'EXTENT':None,'CELL_SIZE':10,
                 'CRS':None,'CREATION_OPTIONS':None,
                 'OUTPUT':parameters[self.OUTPUT]},
                context=context,
                feedback=feedback,
                is_child_algorithm=True,)

            
        else:
            formula = f'if( "{raster.name()}@1" = -9999, -9999, if("{raster.name()}@1"<3,100, if("{raster.name()}@1">8,0,((8-"{raster.name()}@1") / (8-3)*100))))'

            result = processing.run(
                "native:rastercalc", 
                {'LAYERS':[raster],
                 'EXPRESSION':formula,
                 'EXTENT':None,'CELL_SIZE':10,
                 'CRS':None,'CREATION_OPTIONS':None,
                 'OUTPUT':parameters[self.OUTPUT]},
                context=context,
                feedback=feedback,
                is_child_algorithm=True,)

        
 
        return {self.OUTPUT: result['OUTPUT']}
