"""
/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-08-12'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureRequest,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingParameterField,
                       QgsProcessingParameterString,
                       QgsProcessingParameterEnum, 
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFile,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsGeometry,
                       QgsFields,
                       QgsField)

from qgis.analysis import (
    QgsVectorLayerDirector,
    QgsNetworkDistanceStrategy,
    QgsNetworkSpeedStrategy,
    QgsGraphBuilder,
    QgsGraphAnalyzer,
    QgsInterpolator, QgsTinInterpolator
)

from qgis import processing

from collections import OrderedDict, defaultdict
from scipy.spatial import cKDTree
import pandas as pd

class Rasterisation(QgsProcessingAlgorithm):
    """
    Algorithme pour trouver où sont les aménagements cyclables déjà en place
    et où il y a discontinuité
    """
    INPUT = 'INPUT'
    COLAME = 'COLAME'

    
    OUTPUT = 'OUTPUT'
    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Rasteriser le critère'
    
    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Traitements'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Rasterisation()
    def initAlgorithm(self, config):
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Critère à rasteriser'),
                
            )
        )
        
        self.addParameter(QgsProcessingParameterField(self.COLAME, 
                                                      self.tr("Colonne à rasteriser (optionnel)"),
                                                      parentLayerParameterName=self.INPUT,
                                                      optional= True,
                                                      ))
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT,
                self.tr('Raster de sortie')
            )
        )
    
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        inp = self.parameterAsSource(parameters, self.INPUT, context)
        col = self.parameterAsString(parameters, self.COLAME, context)
        output_path = self.parameterAsOutputLayer(parameters, self.OUTPUT, context) #string

        if col:
            raster = processing.run("gdal:rasterize", 
                       {'INPUT': inp,
                        'FIELD':col,
                        'BURN':0,
                        'USE_Z':False,
                        'UNITS':1,
                        'WIDTH':10,'HEIGHT':10,
                        'EXTENT':None,'NODATA':0,
                        'CREATION_OPTIONS':None,
                        'DATA_TYPE':5,'INIT':None,
                        'INVERT':False,'EXTRA':'',
                        'OUTPUT':'memory:'})['OUTPUT']
        else:
            raster = processing.run("gdal:rasterize", 
                       {'INPUT': inp,
                        'FIELD':'',
                        'BURN':0,
                        'USE_Z':False,
                        'UNITS':1,
                        'WIDTH':10,'HEIGHT':10,
                        'EXTENT':None,'NODATA':0,
                        'CREATION_OPTIONS':None,
                        'DATA_TYPE':5,'INIT':None,
                        'INVERT':False,'EXTRA':'',
                        'OUTPUT':'memory:'})['OUTPUT']
        
        result = processing.run("gdal:rastercalculator", 
                       {'INPUT_A':raster,
                        'BAND_A':1,
                        'INPUT_B':None,'BAND_B':None,
                        'INPUT_C':None,'BAND_C':None,
                        'INPUT_D':None,'BAND_D':None,
                        'INPUT_E':None,'BAND_E':None,
                        'INPUT_F':None,'BAND_F':None,
                        'FORMULA':'(A - A.min()) / (A.max() - A.min())',
                        'NO_DATA':None,
                        'EXTENT_OPT':0,'PROJWIN':None,
                        'RTYPE':5,'CREATION_OPTIONS':None,
                        'EXTRA':'',
                        'OUTPUT':'memory:'})
        
        
        
        return {self.OUTPUT: result['OUTPUT']}
        
        