"""
/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-08-12'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureRequest,
                       QgsFeatureSink,
                       QgsProcessingUtils,
                       QgsProcessingException,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingParameterField,
                       QgsProcessingParameterString,
                       QgsProcessingParameterEnum, 
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFile,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsGeometry,
                       QgsFields,
                       QgsField)

from qgis.analysis import (
    QgsVectorLayerDirector,
    QgsNetworkDistanceStrategy,
    QgsNetworkSpeedStrategy,
    QgsGraphBuilder,
    QgsGraphAnalyzer,
    QgsInterpolator, QgsTinInterpolator
)

from qgis import processing
from osgeo import gdal, ogr


from collections import OrderedDict, defaultdict
from scipy.spatial import cKDTree
import pandas as pd
import numpy as np

class Rasterisation(QgsProcessingAlgorithm):
    """
    Algorithme pour trouver où sont les aménagements cyclables déjà en place
    et où il y a discontinuité
    """
    INPUT = 'INPUT'
    COLAME = 'COLAME'

    
    OUTPUT = 'OUTPUT'
    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Rasteriser le critère'
    
    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Traitements'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Rasterisation()
    def initAlgorithm(self, config):
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Critère à rasteriser'),
                
            )
        )
        
        self.addParameter(QgsProcessingParameterField(self.COLAME, 
                                                      self.tr("Colonne à rasteriser (optionnel)"),
                                                      parentLayerParameterName=self.INPUT,
                                                      optional= True,
                                                      ))
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT,
                self.tr('Raster de sortie')
            )
        )
    
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        inp = self.parameterAsSource(parameters, self.INPUT, context)
        col = self.parameterAsString(parameters, self.COLAME, context)
        output_path = self.parameterAsOutputLayer(parameters, self.OUTPUT, context) #string

        if col:
            idx = inp.fields().lookupField(col)
            if idx ==-1:
                raise QgsProcessingException(f"Le champ '{col}' est introuvable dans la couche")

            feedback.pushInfo(f"Colonne détectée : {col}")
            new_layer = inp.materialize(QgsFeatureRequest())

            raster = processing.run("gdal:rasterize", 
                       {'INPUT': new_layer,
                        'FIELD':col,
                        'BURN':0,
                        'USE_Z':False,
                        'UNITS':1,
                        'WIDTH':10,'HEIGHT':10,
                        'EXTENT':None,'NODATA':0,
                        'CREATION_OPTIONS':None,
                        'DATA_TYPE':5,'INIT':None,
                        'INVERT':False,'EXTRA':'',
                        'OUTPUT':QgsProcessingUtils.generateTempFilename(
                            'layer_rasterized.tif', context)})['OUTPUT']
        else:
            raster = processing.run("gdal:rasterize", 
                       {'INPUT': inp,
                        'FIELD':'',
                        'BURN':0,
                        'USE_Z':False,
                        'UNITS':1,
                        'WIDTH':10,'HEIGHT':10,
                        'EXTENT':None,'NODATA':0,
                        'CREATION_OPTIONS':None,
                        'DATA_TYPE':5,'INIT':None,
                        'INVERT':False,'EXTRA':'',
                        'OUTPUT':QgsProcessingUtils.generateTempFilename(
                            'layer_rasterized.tif', context)})['OUTPUT']
        
        feedback.pushInfo('Rasterisation terminée !')
        ds = gdal.Open(raster) if isinstance(raster, str) else raster
        if ds is None:
            raise RuntimeError(f"Impossible d'ouvrir le raster généré : {raster}")
        band = ds.GetRasterBand(1)
        arr = ds.GetRasterBand(1).ReadAsArray().astype(float)
        feedback.pushInfo(f"Dimensions : {ds.RasterXSize} x {ds.RasterYSize} pixels")
        feedback.pushInfo(f"NoData : {band.GetNoDataValue()}")
        feedback.pushInfo(f"Min : {np.nanmin(arr)}, Max : {np.nanmax(arr)}, Moyenne : {np.nanmean(arr):.2f}")
        feedback.pushInfo(f"Valeurs uniques (10 premières) : {np.unique(arr)[:10]}")
        feedback.pushInfo(f"% de pixels à 0 : {(arr == 0).sum() / arr.size * 100:.1f}%")
        
        nodata = band.GetNoDataValue()
        if nodata is not None:
            valid_mask = arr != nodata
        else:
            valid_mask = np.ones(arr.shape, dtype=bool)

        if not valid_mask.any():
            raise QgsProcessingException(
                "Le raster ne contient aucune valeur valide (tout est NoData)."
            )

        r_min = float(arr[valid_mask].min())
        r_max = float(arr[valid_mask].max())
        feedback.pushInfo(f"Densité min={r_min}, max={r_max} (NoData exclu)")

        if r_max == r_min:
            feedback.pushWarning("Toutes les valeurs sont identiques, la normalisation est ignorée.")
            norm = np.zeros_like(arr)
        else:
            norm = np.where(
                valid_mask,
                (arr - r_min) / (r_max - r_min) * 100,
                nodata if nodata is not None else -9999
            )

       
        driver = gdal.GetDriverByName('GTiff')
        out_ds = driver.Create(
            output_path, ds.RasterXSize, ds.RasterYSize, 1, gdal.GDT_Float32
        )
        out_ds.SetGeoTransform(ds.GetGeoTransform())
        out_ds.SetProjection(ds.GetProjection())
        out_band = out_ds.GetRasterBand(1)
        if nodata is not None:
            out_band.SetNoDataValue(nodata)
        out_band.WriteArray(norm.astype(np.float32))
        out_band.FlushCache()
        out_ds = None
        ds = None
        
        
        
        return {self.OUTPUT: output_path}
        
        