# -*- coding: utf-8 -*-
"""
Created on Tue Aug 25 16:28:41 2026

@author: eleonore.lagourgue
"""

"""
/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-08-12'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureRequest,
                       QgsFeatureSink,
                       QgsRasterLayer,
                       QgsProcessingUtils,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingException,
                       QgsProcessingParameterField,
                       QgsProcessingParameterString,
                       QgsProcessingParameterEnum, 
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFile,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsGeometry,
                       QgsVectorLayer,
                       QgsFields,
                       QgsField,
                       QgsDistanceArea)

from qgis.analysis import (
    QgsVectorLayerDirector,
    QgsNetworkDistanceStrategy,
    QgsNetworkSpeedStrategy,
    QgsGraphBuilder,
    QgsGraphAnalyzer,
    QgsInterpolator, QgsTinInterpolator
)

from qgis import processing
from osgeo import gdal


from collections import OrderedDict, defaultdict
from scipy.spatial import cKDTree
import pandas as pd
import numpy as np

class RasterisationPop(QgsProcessingAlgorithm):
    """
    Algorithme pour trouver où sont les aménagements cyclables déjà en place
    et où il y a discontinuité
    """
    INPUT = 'INPUT'
    COLAME = 'COLAME'

    
    OUTPUT = 'OUTPUT'
    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Rasteriser la population'
    
    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Traitements'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return RasterisationPop()
    def initAlgorithm(self, config):
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Critère à rasteriser'),
                
            )
        )
        
        self.addParameter(QgsProcessingParameterField(self.COLAME, 
                                                      self.tr("Colonne de population à rasteriser "),
                                                      parentLayerParameterName=self.INPUT,
                                                      optional= False,
                                                      ))
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT,
                self.tr('Raster de sortie')
            )
        )
    
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        inp = self.parameterAsVectorLayer(parameters, self.INPUT, context)
        col = self.parameterAsString(parameters, self.COLAME, context)
        output_path = self.parameterAsOutputLayer(parameters, self.OUTPUT, context) #string
        
        

        
        d = QgsDistanceArea()
        d.setSourceCrs(inp.crs(), context.transformContext())
        d.setEllipsoid(context.project().ellipsoid() if context.project() else 'WGS84')
        
        FIELD_DENS = 'densite'

        idx = inp.fields().indexFromName(col)
        if idx == -1:
            raise QgsProcessingException(f"Le champ '{col}' est introuvable dans la couche")

        new_layer = inp.materialize(QgsFeatureRequest())
        pr = new_layer.dataProvider()
        new_layer.startEditing()
        pr.addAttributes([ 
                QgsField(FIELD_DENS, QVariant.Double)])
        new_layer.updateFields()
        idx_dens = new_layer.fields().indexFromName(FIELD_DENS)


        min_dens, max_dens = None, None

        for f in new_layer.getFeatures():
            pop = f[idx]
            geom = f.geometry()
            area = d.measureArea(geom)

            if pop is None:
                feedback.pushWarning(f"Feature {f.id()} : population nulle (None), densité mise à 0")
                densite = 0.0
            elif area:
                # Conversion en habitants/km² : les valeurs en hab/m² sont
                # trop petites et s'écrasent facilement à 0 en aval
                densite = (float(pop) / area) * 1_000_000
            else:
                feedback.pushWarning(f"Feature {f.id()} : aire nulle, densité mise à 0")
                densite = 0.0
            f[idx_dens] = densite
            new_layer.changeAttributeValue(f.id(), idx_dens, densite)
            
            min_dens = densite if min_dens is None else min(min_dens, densite)
            max_dens = densite if max_dens is None else max(max_dens, densite)



        if not new_layer.commitChanges():
            raise QgsProcessingException(
                "Impossible de committer les valeurs de densité sur la couche temporaire."
            )
        first_feature = next(new_layer.getFeatures(), None)
        if first_feature is not None:
            feedback.pushInfo(
                f"Vérification — feature id {first_feature.id()} : "
                f"densite = {first_feature[idx_dens]!r}"
            )
        else:
            feedback.pushWarning("new_layer ne contient aucune entité après commit.")

        feedback.pushInfo(f"Densité (hab/km²) — min: {min_dens}, max: {max_dens}")
        
        print(new_layer.featureCount())
        raster = processing.run("gdal:rasterize", 
                       {'INPUT': new_layer,
                        'FIELD':'densite',
                        'BURN':0,
                        'USE_Z':False,
                        'UNITS':1,
                        'WIDTH':20,'HEIGHT':20,
                        'EXTENT':new_layer.extent(),'NODATA':-9999,
                        'CREATION_OPTIONS':None,
                        'DATA_TYPE':6,'INIT':None,
                        'INVERT':False,'EXTRA':'',
                        'OUTPUT':QgsProcessingUtils.generateTempFilename(
                            'pop_rasterized.tif', context)}, 
                            context=context, feedback=feedback)['OUTPUT']
        
        print("Chemin raster:", repr(raster))
        import os
        print("Existe:", os.path.exists(raster))
        
        # test_path = processing.run(
        #     "native:rastercalc", 
        #     {'LAYERS':[raster],
        #      'EXPRESSION':f'(("{raster}@1"- MIN("{raster}@1"))/( MAX("{raster}@1")- MIN("{raster}@1")))*100',
        #      'EXTENT':None,
        #      'CELL_SIZE':None,
        #      'CRS':None,
        #      'CREATION_OPTIONS':None,'OUTPUT':QgsProcessingUtils.generateTempFilename(
        #          'pop_norm.tif', context)}, 
        #          context=context, feedback=feedback)["OUTPUT"]
        # raster_check = QgsRasterLayer(test_path, 'pop_norm')
        # if not raster_check.isValid():
        #     feedback.reportError("Le raster normalisé n'est pas valide.")
        
        
        ds = gdal.Open(raster) if isinstance(raster, str) else raster
        if ds is None:
            raise RuntimeError(f"Impossible d'ouvrir le raster généré : {raster}")
        band = ds.GetRasterBand(1)
        arr = ds.GetRasterBand(1).ReadAsArray().astype(float)
        feedback.pushInfo(f"Dimensions : {ds.RasterXSize} x {ds.RasterYSize} pixels")
        feedback.pushInfo(f"NoData : {band.GetNoDataValue()}")
        feedback.pushInfo(f"Min : {np.nanmin(arr)}, Max : {np.nanmax(arr)}, Moyenne : {np.nanmean(arr):.2f}")
        feedback.pushInfo(f"Valeurs uniques (10 premières) : {np.unique(arr)[:10]}")
        feedback.pushInfo(f"% de pixels à 0 : {(arr == 0).sum() / arr.size * 100:.1f}%")
        
        nodata = band.GetNoDataValue()
        if nodata is not None:
            valid_mask = arr != nodata
        else:
            valid_mask = np.ones(arr.shape, dtype=bool)

        if not valid_mask.any():
            raise QgsProcessingException(
                "Le raster ne contient aucune valeur valide (tout est NoData)."
            )

        r_min = float(arr[valid_mask].min())
        r_max = float(arr[valid_mask].max())
        feedback.pushInfo(f"Densité min={r_min}, max={r_max} (NoData exclu)")

        if r_max == r_min:
            feedback.pushWarning("Toutes les valeurs sont identiques, la normalisation est ignorée.")
            norm = np.zeros_like(arr)
        else:
            norm = np.where(
                valid_mask,
                (arr - r_min) / (r_max - r_min) * 100,
                nodata if nodata is not None else -9999
            )

       
        driver = gdal.GetDriverByName('GTiff')
        out_ds = driver.Create(
            output_path, ds.RasterXSize, ds.RasterYSize, 1, gdal.GDT_Float32
        )
        out_ds.SetGeoTransform(ds.GetGeoTransform())
        out_ds.SetProjection(ds.GetProjection())
        out_band = out_ds.GetRasterBand(1)
        if nodata is not None:
            out_band.SetNoDataValue(nodata)
        out_band.WriteArray(norm.astype(np.float32))
        out_band.FlushCache()
        out_ds = None
        ds = None

        return {self.OUTPUT: output_path}

        
        
        
