# -*- coding: utf-8 -*-
"""
Created on Mon Aug 31 12:57:17 2026


/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-08-12'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterString,
                       QgsProcessingParameterEnum, 
                       QgsProcessingParameterNumber,
                       QgsField,
                       QgsFeature)

from qgis.analysis import (
    QgsVectorLayerDirector,
    QgsNetworkDistanceStrategy,
    QgsNetworkSpeedStrategy,
    QgsGraphBuilder,
    QgsGraphAnalyzer
)
from qgis import processing


class BLOS(QgsProcessingAlgorithm):
    """
    Algorithme pour calculer le résultat final.
    Retourne un raster
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    
    TRAFIC = 'TRAFIC'
    POIDS_TRA = 'POIDS_TRA'

    TRAFIC_PL ='TRAFIC_PL'
    POIDS_PL = 'POIDS_PL'

    NB_VOIES = 'NB_VOIES'
    POIDS_NB = 'POIDS_NB'

    VITESSE = 'VITESSE'
    POIDS_VIT = 'POIDS_VIT'

    LARG_ROUTE = 'LARG_ROUTE'
    POIDS_LAR = 'POIDS_LAR'
    
    PENTE = 'PENTE'
    POIDS_PEN = 'POIDS_PEN'
    
    ACCIDENTS = 'ACCIDENTS'
    POIDS_ACC = 'POIDS_ACC'


    
    
    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return "Calcul du potentiel d'offre des routes"

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Résultat'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return BLOS()
    
    def initAlgorithm(self, config):
        

        # We add the input vector features source. It can have any kind of
        # geometry.
        
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.TRAFIC,
                self.tr('Raster de trafic'),
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.POIDS_TRA,
                self.tr('Poids du trafic'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=1/6,
                minValue=0.0,
            )
        )
        
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.ACCIDENTS,
                self.tr('Raster d"accidents'),
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.POIDS_ACC,
                self.tr('Poids des accidents'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=1/6,
                minValue=0.0,
            )
        )
        
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.TRAFIC_PL,
                self.tr('Raster du trafic de poids lourds'),
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.POIDS_PL,
                self.tr('Poids pour les PL'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=1/6,
                minValue=0.0,
            )
        )
        
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.VITESSE,
                self.tr('Raster de vitesse'),
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.POIDS_VIT,
                self.tr('Poids de la vitesse'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=1/6,
                minValue=0.0,
            )
        )
        
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.PENTE,
                self.tr('Raster de pente'),
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.POIDS_PEN,
                self.tr('Poids de la pente'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=1/6,
                minValue=0.0,
            )
        )
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.LARG_ROUTE,
                self.tr('Raster de la lageur des routes'),
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.POIDS_LAR,
                self.tr('Poids de la largeur'),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=1/6,
                minValue=0.0,
            )
        )
        
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT,
                'Couche de résultat'
            )
        )
        
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        
        # Variables d'environnement
        trafic = self.parameterAsRasterLayer(parameters, self.TRAFIC, context)
        poids_trafic = self.parameterAsDouble(parameters, self.POIDS_TRA, context)
        trafic_pl = self.parameterAsRasterLayer(parameters, self.TRAFIC_PL, context)
        poids_pl = self.parameterAsDouble(parameters, self.POIDS_PL, context)
        accidents = self.parameterAsRasterLayer(parameters, self.ACCIDENTS, context)
        poids_accident = self.parameterAsDouble(parameters, self.POIDS_ACC, context)
        
        
        vitesse = self.parameterAsRasterLayer(parameters, self.VITESSE, context)
        poids_vitesse = self.parameterAsDouble(parameters, self.POIDS_VIT, context)
        pente = self.parameterAsRasterLayer(parameters, self.PENTE, context)
        poids_pente = self.parameterAsDouble(parameters, self.POIDS_PEN, context)
        formula = f'{poids_trafic}*"{trafic.name()}@1" + {poids_accident}*"{accidents.name()}@1" +"{vitesse.name()}@1"*{poids_vitesse} + "{pente.name()}@1"*{poids_pente} + "{trafic_pl.name()}@1"*{poids_pl}'

        
        
        result = processing.run("native:rastercalc", 
                       {'LAYERS':[trafic,trafic_pl, accidents, vitesse, pente],
                        'EXPRESSION':formula,
                        'EXTENT':None,
                        'CELL_SIZE':None,
                        'CRS':None,
                        'CREATION_OPTIONS':None,
                        'OUTPUT':parameters[self.OUTPUT]})
        return {self.OUTPUT: result['OUTPUT']}