"""
/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-08-12'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterString,
                       QgsProcessingParameterEnum, 
                       QgsProcessingParameterNumber)

from qgis.analysis import (
    QgsVectorLayerDirector,
    QgsNetworkDistanceStrategy,
    QgsNetworkSpeedStrategy,
    QgsGraphBuilder,
    QgsGraphAnalyzer
)

from collections import OrderedDict
from scipy.spatial import cKDTree



class TripGeneration(QgsProcessingAlgorithm):
    """
    Algorithme pour générer des trajets
    Soit pour le travail soit pour les services
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    POP = 'POP'
    COLPOP = 'COLPOP'
    IDPOP = 'IDPOP'
    
    RESEAU = 'RESEAU'
    ACCIDENTS = "ACCIDENTS"
    VITESSE = 'VITESSE'
    OD = 'OD'
    ORIGINE = "ORIGINE"
    DESTINATION = "DESTINATION"
    
    SERVICES = 'SERVICES'
    IDSERV = 'IDSERV'
    
    DIRECTION_FIELD = 'DIRECTION_FIELD'
    VALUE_FORWARD = 'VALUE_FORWARD'
    VALUE_BACKWARD = 'VALUE_BACKWARD'
    VALUE_BOTH = 'VALUE_BOTH'
    DEFAULT_DIRECTION = 'DEFAULT_DIRECTION'
    SPEED_FIELD = 'SPEED_FIELD'
    DEFAULT_SPEED = 'DEFAULT_SPEED'
    TOLERANCE = 'TOLERANCE'


    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Génération de trajets'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Traitements'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return TripGeneration()
    
    
    def initAlgorithm(self, config):
        
        self.DIRECTIONS = OrderedDict([
        ('Forward direction', QgsVectorLayerDirector.DirectionForward),
        ('Backward direction', QgsVectorLayerDirector.DirectionBackward),
        ('Both directions', QgsVectorLayerDirector.DirectionBoth)])
        
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.POP,
                self.tr('Couche de population (point)'),
                [QgsProcessing.SourceType.TypeVectorPoint]
            )
        )
        self.addParameter(
            QgsProcessingParameterField(self.IDPOP, 
                                                      "Colonne id pour la couche de population",
                                                      parentLayerParameterName=self.POP))
        self.addParameter(
            QgsProcessingParameterField(self.COLPOP, 
                                                      "Colonne population pour la couche de population",
                                                      parentLayerParameterName=self.POP,
                                                      optional = True))
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.RESEAU,
                self.tr('Réseau'),
                [QgsProcessing.SourceType.TypeVectorLine]
            )
        )
        self.addParameter(QgsProcessingParameterField(self.DIRECTION_FIELD, 
                                                      self.tr("Colonne direction"),
                                                      parentLayerParameterName=self.RESEAU,
                                                      optional= True))
        self.addParameter(QgsProcessingParameterString(self.VALUE_FORWARD, 
                                                       self.tr("Sens direct (à remplir si la colonne de direction est renseignée)"),
                                                       optional=True,
                                                       defaultValue=None))
        self.addParameter(QgsProcessingParameterString(self.VALUE_BACKWARD, 
                                                       self.tr("Sens inverse (à remplir si la colonne de direction est renseignée)"),
                                                       optional = True,
                                                       defaultValue=None))
        self.addParameter(QgsProcessingParameterString(self.VALUE_BOTH, 
                                                       self.tr("Double sens (à remplir si la colonne de direction est renseignée)"),
                                                       optional=True,
                                                       defaultValue=None))
        self.addParameter(QgsProcessingParameterEnum(self.DEFAULT_DIRECTION,
                                                 self.tr("Direction par défaut"),
                                                 list(self.DIRECTIONS.keys()),
                                                 optional = True,
                                                 defaultValue=None))
        self.addParameter(QgsProcessingParameterField(self.SPEED_FIELD, 
                                                      self.tr("Colonne vitesse"), 
                                                      parentLayerParameterName=self.RESEAU,
                                                      optional=True))
        self.addParameter(QgsProcessingParameterString(self.DEFAULT_SPEED, self.tr("Vitesse par défaut"), defaultValue=50))
        
        #Destinations
        self.addParameter(QgsProcessingParameterFile(self.OD_MATRIX, "Matrice OD"))

        self.addParameter(QgsProcessingParameterString(self.ORIGINE, 
                                                       "Colonne origine"))
        self.addParameter(QgsProcessingParameterString(self.DESTINATION, 
                                                      "Colonne destination",
                                                      ))
        self.addParameter(QgsProcessingParameterString(self.COMPTEUR, 
                                                      "Colonne renseignant le volume de flux entre origine et destination",
                                                      ))
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.SERVICES,
                self.tr('Couche de services (point)'),
                [QgsProcessing.SourceType.TypeVectorPoint],
                optional = True
            )
        )                  
        self.addParameter(
            QgsProcessingParameterField(self.IDSERV, 
                                               "Colonne id pour la couche de population",
                                               parentLayerParameterName=self.SERVICES,
                                               optional = True))                          
        self.addParameter(QgsProcessingParameterNumber(self.TOLERANCE, self.tr("Tolérance topologique (en mètres)"), defaultValue=0.0))

    
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        pop = self.parameterAsSource(parameters, self.POP, context)
        id_pop = self.parameterAsString(parameters, self.IDPOP,context)

        reseau = self.parameterAsVectorLayer(parameters, self.RESEAU, context)
        tolerance = self.parameterAsDouble(parameters, self.TOLERANCE, context)
        colonne_direction = self.parameterAsString(parameters, self.DIRECTION_FIELD, context)
        value_forward = self.parameterAsString(parameters, self.VALUE_FORWARD, context)
        value_backward = self.parameterAsString(parameters, self.VALUE_BACKWARD, context)
        value_both = self.parameterAsString(parameters, self.VALUE_BOTH, context)
        default_direction = self.parameterAsString(parameters, self.DEFAULT_DIRECTION, context)


        services = self.parameterAsSource(parameters, self.SERVICES, context)#QgsProcessingFeatureSource
        pop_column = self.parameterAsString(parameters, self.COLPOP,context)
        id_service = self.parameterAsString(parameters, self.IDSERV,context)

        if (services is None and pop_column is not None) or (services is not None and pop_column is None):
            feedback.pushWarning(" Erreur : il manque une des deux informations \n Colonne population ou couche de services")
            break
        
        
        director = QgsVectorLayerDirector(
            reseau,
            -1,        # index du champ de direction (-1 si pas de sens unique)
            value_forward,        # valeur "sens direct"
            value_backward,        # valeur "sens inverse"
            value_both,        # valeur "double sens"
            QgsVectorLayerDirector.DirectionBoth  # direction par défaut
        )
        strategy = QgsNetworkDistanceStrategy()
        director.addStrategy(strategy)
        crs = reseau.crs()
        builder = QgsGraphBuilder(crs)
        
        
        #my_lyr = QgsVectorLayer('Linestring?crs=epsg:2154', 'network result', 'memory')
        Points_dep = []
        NbPop =[]
        for feat in pop.getFeatures():
            geom = feat.geometry().asPoint()
            if pop_column is not None:
                nb_pop = feat[pop_column]
                NbPop.add(nb_pop)
            Points_dep.add(geom)
        if services is not None:
            Points_arr =[]
            for feat in services.getFeatures():
                geom = feat.geometry().asPoint()
                Points_arr.add(geom)
            
            Points = Points_dep +Points_arr
            tiedPoints = director.makeGraph(builder, [Points]) 
            graph = builder.graph()
            
            result = processing.run("qgis:distancematrix", {
                'INPUT': pop,'INPUT_FIELD':'AXE',
                'TARGET':services,'TARGET_FIELD':'id',
                'MATRIX_TYPE':0,'NEAREST_POINTS':1,
                'OUTPUT':'TEMPORARY_OUTPUT'})['OUTPUT']
            
            n_orig = len(pop.getFeatures())
            vertex_origines = [graph.findVertex(tied_points[i]) for i in range(n_orig)]
            vertex_destinations = [graph.findVertex(tied_points[n_orig + j]) for j in range(len(services.getFeatures()))]
            results = []
            
            for i, v_orig in enumerate(vertex_origines):
                if feedback.isCanceled():
                            break
                (tree, cost) = QgsGraphAnalyzer.dijkstra(graph, startId, 0)
                for j, v_dest in enumerate(vertex_destinations):
                    if tree[v_dest] == -1 and v_dest != v_orig:
                        feedback.pushWarning(f"Pas de chemin entre origine {i} et destination {j}")
                        continue
        
                    # Reconstruction du chemin en remontant les arêtes depuis la destination
                    path_vertices = []
                    current = v_dest
                    while current != v_orig:
                        path_vertices.append(current)
                        edge_id = tree[current]
                        if edge_id == -1:
                            break
                        edge = graph.edge(edge_id)
                        current = edge.fromVertex()
                    path_vertices.append(v_orig)
                    path_vertices.reverse()
        
                    # Construction de la géométrie ligne à partir des sommets
                    points = [graph.vertex(v).point() for v in path_vertices]
                    geom = QgsGeometry.fromPolylineXY(points)
        
                    results.append({
                        'origine_idx': i,
                        'destination_idx': j,
                        'distance': cost[v_dest],
                        'geometry': geom
                    })
        else:
            vertex_origines = [graph.findVertex(tied_points[i]) for i in range(n_orig)]
            results = []
            for i, v_orig in enumerate(vertex_origines):
                if feedback.isCanceled():
                            break
                (tree, cost) = QgsGraphAnalyzer.dijkstra(graph, startId, 0)
    
                for j , v_dest in enumerate(vertex_origines):
                    if i =! j:
                        if tree[v_dest] == -1 and v_dest != v_orig:
                            feedback.pushWarning(f"Pas de chemin entre origine {i} et destination {j}")
                            continue
                        path_vertices = []
                        current = v_dest
                        while current != v_orig:
                            path_vertices.append(current)
                            edge_id = tree[current]
                            if edge_id == -1:
                                break
                            edge = graph.edge(edge_id)
                            current = edge.fromVertex()
                        path_vertices.append(v_orig)
                        path_vertices.reverse()
            
                        # Construction de la géométrie ligne à partir des sommets
                        points = [graph.vertex(v).point() for v in path_vertices]
                        geom = QgsGeometry.fromPolylineXY(points)
            
                        results.append({
                            'origine_idx': i,
                            'destination_idx': j,
                            'distance': cost[v_dest],
                            'geometry': geom
                        })
                        
                        
        for r in results:
        feat = QgsFeature(fields)
        feat.setGeometry(r['geometry'])
        feat.setAttributes([r['origine_idx'], r['destination_idx'], r['distance']])
        sink.addFeature(feat, QgsFeatureSink.FastInsert)
        
        return {self.OUTPUT: dest_id}
    
    def find_nearest_service(self, pop, services, geom_pop, geom_services):
        
        result = processing.run("qgis:distancematrix", {
            'INPUT': pop,'INPUT_FIELD':'AXE',
            'TARGET':services,'TARGET_FIELD':'id',
            'MATRIX_TYPE':0,'NEAREST_POINTS':1,
            'OUTPUT':'TEMPORARY_OUTPUT'})['OUTPUT']
        coords = np.array(list(zip(geom_pop.geometry.x(), geom_pop.geometry.y())))
        coords_recherche = np.array(list(zip(geom_services.geometry.x(), geom_services.geometry.y())))
        tree = cKDTree(coords_recherche)
        distances, indices = tree.query(coords)
        nearest_services = service.loc[indices]
        print(nearest_services)
        return indices