# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-08-12'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterString,
                       QgsProcessingParameterEnum, 
                       QgsProcessingParameterNumber,
                       QgsFeatureRequest,
                       QgsField,
                       QgsFeature)

from qgis.analysis import (
    QgsVectorLayerDirector,
    QgsNetworkDistanceStrategy,
    QgsNetworkSpeedStrategy,
    QgsGraphBuilder,
    QgsGraphAnalyzer
)
from qgis import processing
import math

class AjoutTrafic(QgsProcessingAlgorithm):
    """
    Algorithme pour ajouter l'information de trafic depuis une couche de points à une couche de
    noeuds.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    RESEAU = 'RESEAU'
    MAXDIST = "MAXDIST"
    SPEED_FIELD = 'SPEED_FIELD'
    DIRECTION_FIELD = 'DIRECTION_FIELD'
    TRAFIC_PL = 'TRAFIC_PL'
    NATURE_FIELD = 'NATURE_FIELD'

    

    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Ajouter le trafic'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Formatage'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return AjoutTrafic()
    
    def initAlgorithm(self, config):
        

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Couche de trafic (point)'),
                [QgsProcessing.SourceType.TypeVectorPoint]
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.RESEAU,
                self.tr('Couche de réseau (lignes)'),
                [QgsProcessing.SourceType.TypeVectorLine]
            )
        )
        self.addParameter(QgsProcessingParameterField(self.DIRECTION_FIELD, 
                                                      self.tr("Colonne nom"),
                                                      parentLayerParameterName=self.RESEAU,
                                                      optional= False))
        
        self.addParameter(QgsProcessingParameterField(self.NATURE_FIELD, 
                                                      self.tr("Colonne de nature ou d'importance"),
                                                      parentLayerParameterName=self.RESEAU,
                                                      optional= False))
        self.addParameter(QgsProcessingParameterField(self.SPEED_FIELD, 
                                                      self.tr("Colonne trafic"), 
                                                      parentLayerParameterName=self.INPUT,
                                                      optional=False))
        self.addParameter(QgsProcessingParameterField(self.TRAFIC_PL, 
                                                       self.tr("Colonne trafic poids lourds (si existe)"), 
                                                       parentLayerParameterName=self.INPUT,
                                                       optional=True))
        
       
        
        self.addParameter(
            QgsProcessingParameterNumber(
                self.MAXDIST, 
                self.tr("Distance maximum entre les entités"),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=2.0))

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsVectorLayer(parameters, self.INPUT, context)
        reseau = self.parameterAsVectorLayer(parameters, self.RESEAU, context)
        
        max_dist  = self.parameterAsDouble(parameters, self.MAXDIST, context)  # tolérance en unités de la couche
        field_trafic = self.parameterAsString(parameters, self.SPEED_FIELD, context)
        field_nom = self.parameterAsString(parameters, self.DIRECTION_FIELD, context)
        field_pl = self.parameterAsString(parameters, self.TRAFIC_PL, context)
        field_nature = self.parameterAsString(parameters, self.NATURE_FIELD, context)

        
        new_layer = source.materialize(QgsFeatureRequest().setFilterFids(source.allFeatureIds()))
        
        #Vérification
        pr = new_layer.dataProvider()
        existing = set(new_layer.fields().names())
        print(existing)
        to_add =[]
        if 'pos_key' not in existing:
            
            to_add = [           
              QgsField('pos_key', QVariant.String)            
                  ]
        
        #to_add = [QgsField('pos_key', QVariant.String) if 'pos_key' not in existing]
        if to_add:
            pr.addAttributes(to_add)
            new_layer.updateFields()
            feedback.pushInfo(f"Added:, {[f.name() for f in to_add]}")
        else:
            feedback.pushInfo("Rien à ajouter")
        
        print(new_layer.fields().names())
        idx_key = new_layer.fields().indexOf('pos_key')
        
        features = list(new_layer.getFeatures())
        new_layer.startEditing()

        precision=6
        groups = {}
        for feat in features:
            geom = feat.geometry()
            pt = geom.asPoint()  
            key = f"{round(pt.x(), precision)}_{round(pt.y(), precision)}"
            new_layer.changeAttributeValue(feat.id(), idx_key, key)
            groups.setdefault(key, []).append(feat)
        
            
        new_layer.commitChanges()
        
        aggregates = [
            {
                'aggregate': 'mean',
                'delimiter': ',',
                'input': field_trafic,
                'length': 11,
                'name': field_trafic,
                'precision': 2,
                'sub_type': 0,
                'type': 6,  # Double
                'type_name': 'double'
            }
        ]

        if field_pl:
            aggregates.append({
                'aggregate': 'sum',
                'delimiter': ',',
                'input': field_pl,
                'length': 11,
                'name': field_pl,
                'precision': 2,
                'sub_type': 0,
                'type': 6,
                'type_name': 'double'
            })
        cpt_aggre = processing.run("native:aggregate", 
                       {'INPUT': new_layer,
                        'GROUP_BY':'pos_key',
                        'AGGREGATES':aggregates,
                        'OUTPUT':'memory:compteurs_moyennes'
                        },  context=context, feedback=feedback)['OUTPUT']
        feedback.pushInfo(str(cpt_aggre.featureCount()))
        # for feat in source.getFeatures():
        #     geom =feat.geometry()
        #     pt = geom.asPoint()  
            
        result = processing.run("native:joinbynearest", 
                       {'INPUT':reseau,'INPUT_2': cpt_aggre,
                        'FIELDS_TO_COPY':[],
                        'DISCARD_NONMATCHING':False,
                        'PREFIX':'','NEIGHBORS':1,
                        'MAX_DISTANCE':max_dist,'OUTPUT': 'memory:jointure'}
                       , context=context, feedback=feedback)['OUTPUT']
        feedback.pushInfo(str(result.featureCount()))
        idx_trafic = result.fields().indexOf(field_trafic)
        if field_pl:
            idx_pl = result.fields().indexOf(field_pl)
    
        feats = {f.id(): f for f in result.getFeatures()}
    
        def endpoints(fid):
            # Trouve les points de début et de fin
            geom = feats[fid].geometry()
            line = geom.asMultiPolyline()[0] if geom.isMultipart() else geom.asPolyline()
            return (line[0], line[-1])
        def get_rank(value):
            """
            Retourne un rang numérique où 0 = le plus important.
            Gère à la fois:
              - une chaîne de caractères (nature de la voie)
              - un entier 1-6 (champ 'importance' de la BD Topo, 1 = le plus important)
            """
            PRIORITY_ORDER = ["Autoroute","motorway", "motorway_link","trunk","trunk_link","primary", "primary_link", "Nationale", "Départementale",
                              "secondary", "secondary_link", "tertiary", "tertiary_link"]
            if value is None:
                return len(PRIORITY_ORDER) + 6  # inconnu = le moins prioritaire possible
        
            # Cas numérique (importance BD Topo, 1 à 6)
            if isinstance(value, (int, float)):
                return int(value) - 1  # 1 -> 0, 2 -> 1, ..., 6 -> 5
        
            # Cas chaîne numérique éventuelle ("3" au lieu de 3)
            if isinstance(value, str) and value.strip().isdigit():
                return int(value.strip()) - 1
        
            # Cas chaîne de caractères type "Autoroute", "primary", etc.
            try:
                return PRIORITY_ORDER.index(value)
            except ValueError:
                return len(PRIORITY_ORDER) + 6
                  
        def _direction_away(fid, shared_key):
            
            """
            Vecteur normalisé partant du nœud partagé (shared_key) vers
            l'intérieur du tronçon fid (point suivant sur la ligne).
            """
            geom = feats[fid].geometry()
            line = geom.asMultiPolyline()[0] if geom.isMultipart() else geom.asPolyline()
            start, end = line[0], line[-1]
            
            start_key = (round(start.x(), precision), round(start.y(), precision))
            if start_key == shared_key:
                nxt = line[1] if len(line) > 1 else end
                dx, dy = nxt.x() - start.x(), nxt.y() - start.y()
            else:
                nxt = line[-2] if len(line) > 1 else start
                dx, dy = nxt.x() - end.x(), nxt.y() - end.y()
            norm = (dx ** 2 + dy ** 2) ** 0.5
            return (dx / norm, dy / norm) if norm else (0.0, 0.0)

        def is_continuation(fid_a, fid_b, shared_key, angle_max_deg=45):
            """
            Pour regarder si un tronçon est bien la continuité du premier ou non
            selon l'angle entre les deux géométries
            """
            vax, vay = _direction_away(fid_a, shared_key)
            vbx, vby = _direction_away(fid_b, shared_key)
            cos_angle = max(-1.0, min(1.0, vax * vbx + vay * vby))
            angle = math.degrees(math.acos(cos_angle))
            return angle >= (180 - angle_max_deg)
        
        
            def slope(x1, y1, x2, y2): # Line slope given two points:
                return (y2-y1)/(x2-x1)
            
            def angle(s1, s2): 
                return math.degrees(math.atan((s2-s1)/(1+(s2*s1))))

                
        # index des noeuds : {coord arrondie: [fid, fid, ...]}
        vertex_index = {}
        for fid in feats.keys():
            for pt in endpoints(fid):
                key = (round(pt.x(), precision), round(pt.y(), precision))
                vertex_index.setdefault(key, []).append(fid)
    
        queue = [fid for fid, f in feats.items() if f[field_trafic] not in (None, 'NULL')]
    
        result.startEditing()
    
        while queue:
            current_fid = queue.pop(0)
            current_val = feats[current_fid][field_trafic]
            current_nom = feats[current_fid][field_nom]
            current_nature = feats[current_fid][field_nature]
            rank = get_rank(current_nature)
            if field_pl:
                current_pl = feats[current_fid][field_pl]
                for pt in endpoints(current_fid):
                    key = (round(pt.x(), precision), round(pt.y(), precision))
                    neighbors = vertex_index.get(key, [])
                    blocked = False
                    if len(neighbors) > 2:
                        for n_fid in neighbors:
                            if n_fid == current_fid:
                                continue
                            n_feat = feats[n_fid]
                            if n_feat[field_nom] == current_nom:
                                continue  # même nom, pas une "autre route"
                            nature = n_feat[field_nature]
                            n_rank = get_rank(nature)
                            if n_rank<= rank :
                                blocked = True
                                break
                    if blocked:
                        continue  # vraie intersection avec un axe important, on ne propage pas ici
                    
                    #Propager la valeur aux tronçons de même nom sans valeur
                    for n_fid in neighbors:
                        if n_fid == current_fid:
                            continue
                        n_feat = feats[n_fid]
            
                        if n_feat[field_trafic] not in (None, 'NULL'):
                            continue  # déjà une valeur
            
                        if n_feat[field_nom] != current_nom:
                            continue  # nom différent, on ne propage pas
                            
                        if not is_continuation(current_fid, n_fid, key):
                            continue  # angle trop marqué : route qui croise, pas qui prolonge

        
                        result.changeAttributeValue(n_fid, idx_trafic, current_val)
                        result.changeAttributeValue(n_fid, idx_pl, current_pl)
                        n_feat.setAttribute(idx_trafic, current_val)
                        n_feat.setAttribute(idx_pl, current_pl)

                        queue.append(n_fid)
            
            else:
                for pt in endpoints(current_fid):
                    key = (round(pt.x(), precision), round(pt.y(), precision))
                    neighbors = vertex_index.get(key, [])
                    blocked = False
                    if len(neighbors) > 2:
                        for n_fid in neighbors:
                            if n_fid == current_fid:
                                continue
                            n_feat = feats[n_fid]
                            if n_feat[field_nom] == current_nom:
                                continue  # même nom, pas une "autre route"
                            nature = n_feat[field_nature]
                            n_rank = get_rank(nature)
                            if n_rank<= rank :
                                blocked = True
                                break
                    if blocked:
                        continue  # vraie intersection avec un axe important, on ne propage pas ici
                    
                    #Propager la valeur aux tronçons de même nom sans valeur
                    for n_fid in neighbors:
                        if n_fid == current_fid:
                            continue
                        n_feat = feats[n_fid]
            
                        if n_feat[field_trafic] not in (None, 'NULL'):
                            continue  # déjà une valeur
            
                        if n_feat[field_nom] != current_nom:
                            continue  # nom différent, on ne propage pas
                            
                        if not is_continuation(current_fid, n_fid, key):
                            continue  # angle trop marqué : route qui croise, pas qui prolonge
    
        
                        result.changeAttributeValue(n_fid, idx_trafic, current_val)
                        n_feat.setAttribute(idx_trafic, current_val)
                        queue.append(n_fid)
                                
                      #vraie intersection -> on ne propage pas à travers ce noeud
    
                
    
        result.commitChanges()
        
        
        
        
        
        (sink, dest_id) = self.parameterAsSink(
        parameters, self.OUTPUT, context,
        result.fields(), result.wkbType(), result.sourceCrs()
        )
        for feat in result.getFeatures():
            sink.addFeature(feat, QgsFeatureSink.FastInsert)
        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        
        
        
        return {self.OUTPUT: dest_id}

