# -*- coding: utf-8 -*-
"""
Created on Thu Sep 10 09:48:39 2026


/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-08-12'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsProcessingUtils,
                       QgsFeatureRequest,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterString,
                       QgsProcessingParameterEnum, 
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFile,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsGeometry,
                       QgsFields,
                       QgsField)

from qgis.analysis import (
    QgsVectorLayerDirector,
    QgsNetworkDistanceStrategy,
    QgsNetworkSpeedStrategy,
    QgsGraphBuilder,
    QgsGraphAnalyzer
)
from qgis import processing
from osgeo import gdal, ogr


from collections import OrderedDict, defaultdict
from scipy.spatial import cKDTree
import pandas as pd
import numpy as np

from qgis.core import QgsApplication


class Amenagement(QgsProcessingAlgorithm):
    RESEAU = 'RESEAU'
    COLVIT = 'COLVIT'
    SOURCE = 'SOURCE'
    RASTER_RESULT = "RASTER_RESULT"
    
    TRAFIC_VELO = "TRAFIC_VELO"
    TRAFIC_VL = "TRAFIC_VL"
    
    OUTPUT = 'OUTPUT'

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Evaluation des aménagements possibles'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Traitements'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Amenagement()
    
    def initAlgorithm(self, config):
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.RESEAU,
                self.tr('Les tronçons sélectionnés'),
                [QgsProcessing.SourceType.TypeVectorLine]
            )
        )
        self.addParameter(QgsProcessingParameterField(self.COLVIT, 
                                                      self.tr("Colonne vitesse"),
                                                      parentLayerParameterName=self.RESEAU,
                                                      optional= False,
                                                      ))
        
    
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        reseau = self.parameterAsSource(parameters, self.RESEAU, context)
