"""
/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-08-12'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsProcessingUtils,
                       QgsFeatureRequest,
                       QgsFeatureSink,
                       QgsRasterLayer,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterString,
                       QgsProcessingParameterEnum, 
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFile,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsGeometry,
                       QgsFields,
                       QgsField)

from qgis.analysis import (
    QgsVectorLayerDirector,
    QgsNetworkDistanceStrategy,
    QgsNetworkSpeedStrategy,
    QgsGraphBuilder,
    QgsGraphAnalyzer
)
from qgis import processing
from osgeo import gdal, ogr


from collections import OrderedDict, defaultdict
from scipy.spatial import cKDTree
import pandas as pd
import numpy as np
import math

from qgis.core import QgsApplication

def resolve_grass_alg(short_name):
    """
    Trouve l'ID complet d'un algorithme GRASS quel que soit
    le préfixe (grass:, grass7:, grass8:) utilisé par la
    version de QGIS/GRASS installée.
    """
    registry = QgsApplication.processingRegistry()
    for alg in registry.algorithms():
        if alg.id().endswith(short_name):
            return alg.id()
    return None

def build_expr(columns, is_not_null=True):
    
    if is_not_null:
        op = "IS NOT NULL" 
        conditions = [f'"{col}" {op}' for col in columns]
        return " OR ".join(conditions)
    else:
        op = "IS NULL" 
        conditions = [f'"{col}" {op}' for col in columns]
        return " AND ".join(conditions)


# Profils par source : pour chaque source de données connue, on associe à
# chaque nom de colonne la liste des valeurs qui indiquent réellement un
# aménagement cyclable. Une colonne non listée dans le profil retombe sur
# IS NOT NULL (en excluant les valeurs "vides de sens" ci-dessous).
#
# Pour ajouter une nouvelle source : ajoute une entrée ici avec les noms de
# colonnes et valeurs réels de ton jeu de données (à vérifier dans la table
# attributaire QGIS ou la documentation du fournisseur).
SOURCE_PROFILES = {
    'OSM': {
        'highway': ['cycleway'],
        'cycleway': ['track', 'lane', 'shared_lane', 'opposite',
                     'opposite_lane', 'opposite_track'],
        'cycleway:left': ['track', 'lane', 'shared_lane', 'opposite_track'],
        'cycleway:right': ['track', 'lane', 'shared_lane', 'opposite_track'],
        'cycleway:both': ['track', 'lane', 'shared_lane'],
        'bicycle': ['designated'],
        'bicycle_road': ['yes'],
    },
    'IGN BD TOPO': {
        # Classe "Tronçon de route" : la piste cyclable en site propre est
        # une Nature à part entière ; les aménagements sur voirie partagée
        # (bande, voie verte, vélorue...) sont dans "Nature de la restriction".
        # Les noms de champs shapefile peuvent être tronqués (10 caractères) :
        # adapte 'nature' / 'nature_de_la_restriction' au nom réel dans ta couche.
        'nature': ['Piste cyclable'],
        'nature_de_la_restriction': [
            'Piste cyclable', 'Voie verte', 'Vélorue',
            'Chaussée à voie centrale banalisée',
            'Aménagement mixte hors voie verte',
            'Double sens cyclable non matérialisé',
        ],
    },
}

# Valeurs qui, même non nulles, signifient explicitement "pas d'aménagement",
# utilisées en repli pour une colonne sans profil connu, ou en mode Personnalisé.
NO_FACILITY_VALUES = ['no', 'none', 'Aucun', 'Non', 'Sans objet', 'Sans valeur']

def build_cycling_expr(columns, profile=None, custom_values=None, presence=True):
    """
    Construit une expression QGIS qui sélectionne (presence=True) ou exclut
    (presence=False) les segments avec un aménagement cyclable.

    - profile : dict {colonne: [valeurs valides]} issu de SOURCE_PROFILES,
      ou None si on utilise custom_values.
    - custom_values : liste de valeurs (mode "Personnalisé") appliquée telle
      quelle à TOUTES les colonnes sélectionnées, utile pour une source non
      répertoriée dans SOURCE_PROFILES.
    """
    profile = profile or {}
    conditions = []
    for col in columns:
        valid_values = profile.get(col) or custom_values
        if valid_values:
            values_str = ", ".join(f"'{v}'" for v in valid_values)
            if presence:
                cond = f'"{col}" IN ({values_str})'
            else:
                # NULL-safe : un champ NULL ne peut pas satisfaire "IN (...)",
                # donc il ne peut pas non plus satisfaire "NOT IN (...)" en
                # logique à trois valeurs (NULL, pas TRUE). On le traite
                # explicitement comme une absence d'aménagement.
                cond = f'("{col}" IS NULL OR "{col}" NOT IN ({values_str}))'
        else:
            # Ni profil ni valeurs personnalisées pour cette colonne :
            # on retombe sur "non nul et différent des valeurs 'vides'"
            no_values_str = ", ".join(f"'{v}'" for v in NO_FACILITY_VALUES)
            if presence:
                cond = f'"{col}" IS NOT NULL AND "{col}" NOT IN ({no_values_str})'
            else:
                cond = f'("{col}" IS NULL OR "{col}" IN ({no_values_str}))'
        conditions.append(cond)

    # On construit l'expression
    # voulue pour chaque mode :
    # - présence = au moins une colonne indique un aménagement (OR)
    # - absence  = aucune colonne n'indique un aménagement (AND)
    if presence:
        return " OR ".join(conditions)
    return " AND ".join(conditions)

    
class AnalyseExistant(QgsProcessingAlgorithm):
    """
    Algorithme pour trouver où sont les aménagements cyclables déjà en place
    et où il y a discontinuité
    """
    RESEAU = 'RESEAU'
    COLAME = 'COLAME'
    SOURCE = 'SOURCE'
    VALEURS_PERSONNALISEES = 'VALEURS_PERSONNALISEES'
    
    
    OUTPUT = 'OUTPUT'

    # Ordre des options affichées dans le menu déroulant SOURCE
    SOURCE_OPTIONS = list(SOURCE_PROFILES.keys()) + ['Personnalisé']
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Analyse discontinuité des aménagements cyclables'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Traitements'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return AnalyseExistant()
    
    def initAlgorithm(self, config):
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.RESEAU,
                self.tr('Réseau'),
                [QgsProcessing.SourceType.TypeVectorLine]
            )
        )
        
        self.addParameter(QgsProcessingParameterField(self.COLAME, 
                                                      self.tr("Colonne(s) aménagements"),
                                                      parentLayerParameterName=self.RESEAU,
                                                      optional= False,
                                                      allowMultiple = True))

        self.addParameter(
            QgsProcessingParameterEnum(
                self.SOURCE,
                self.tr("Source des données (détermine les valeurs valides par colonne)"),
                options=self.SOURCE_OPTIONS,
                defaultValue=0
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.VALEURS_PERSONNALISEES,
                self.tr(
                    "Valeurs indiquant un aménagement (mode Personnalisé uniquement, "
                    "séparées par des virgules, ex: Piste cyclable,Bande cyclable)"
                ),
                optional=True
            )
        )
        
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT,
                self.tr('Output raster')
            )
        )
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        reseau = self.parameterAsSource(parameters, self.RESEAU, context)
        col_ame = self.parameterAsStrings(parameters, self.COLAME, context)

        source_idx = self.parameterAsEnum(parameters, self.SOURCE, context)
        source_name = self.SOURCE_OPTIONS[source_idx]
        valeurs_perso_str = self.parameterAsString(parameters, self.VALEURS_PERSONNALISEES, context)

        if source_name == 'Personnalisé':
            profile = None
            custom_values = [v.strip() for v in valeurs_perso_str.split(',') if v.strip()] or None
            if not custom_values:
                feedback.pushWarning(
                    "Mode Personnalisé sans valeurs renseignées : repli sur "
                    "IS NOT NULL (hors valeurs 'vides' usuelles) pour toutes les colonnes."
                )
        else:
            profile = SOURCE_PROFILES.get(source_name, {})
            custom_values = None

        feedback.pushInfo(f"Colonnes sélectionnées : {col_ame} (source : {source_name})")
        # 1.Extraire les routes avec aménagements
        expr = build_cycling_expr(col_ame, profile=profile, custom_values=custom_values, presence=True)
        feedback.pushInfo(f"Expression aménagements : {expr}")
        request = QgsFeatureRequest().setFilterExpression(expr)
        velo = reseau.materialize(request)
        print("Nb entités:", velo.featureCount())

        # 2.Trouver les trous
        # a.Calculer les composantes connexes
        alg_id = resolve_grass_alg("v.net.components")
        if alg_id is None:
            raise RuntimeError(
                "L'algorithme GRASS v.net.components est introuvable. "
                "Vérifiez que le fournisseur GRASS est activé dans "
                "Traitement > Options > Fournisseurs."
            )
        result_pts = processing.run(
            alg_id, 
            {'input':velo,
             'points':None,
             'threshold':50,
             'method':0,
             'arc_column':'',
             'arc_backward_column':'',
             'node_column':'','-a':True,
             'output':'memory:ligne',
             'output_point':'memory:points',
             'GRASS_REGION_PARAMETER':None,
             'GRASS_SNAP_TOLERANCE_PARAMETER':-1,
             'GRASS_MIN_AREA_PARAMETER':0.0001,
             'GRASS_OUTPUT_TYPE_PARAMETER':0,'GRASS_VECTOR_DSCO':'',
             'GRASS_VECTOR_LCO':'','GRASS_VECTOR_EXPORT_NOCAT':False}
            , context=context, feedback=feedback)
        
        velo_lines = result_pts['output']
        #velo_nodes = result_pts['output_point']
        
        # b.Trouver les routes connectant différentes composantes connexes
        
        
        expr_sans = build_cycling_expr(col_ame, profile=profile, custom_values=custom_values, presence=False)
        feedback.pushInfo(f"Expression sans aménagement : {expr_sans}")
        request_sans = QgsFeatureRequest().setFilterExpression(expr_sans)
        sans_ame = reseau.materialize(request_sans)
        feedback.pushInfo(f"Segments sans aménagement : {sans_ame.featureCount()}")
        print("Nb entités sans aménagements:", sans_ame.featureCount())
        
        
        
        # On cherche les tronçons entre deux aménagements
        def slope(x1, y1, x2, y2): # Line slope given two points:
            return (y2-y1)/(x2-x1)
        
        def angle(s1, s2): 
            return math.degrees(math.atan((s2-s1)/(1+(s2*s1))))
        
        ame_feat = [feat for feat in velo.getFeatures()]
        trou = []
        for feat in sans_ame.getFeatures():
            geometry = feat.geometry()
            voisins =[]
            line = geometry.asMultiPolyline()[0] if geometry.isMultipart() else geometry.asPolyline()
            start, end = line[0], line[-1]
            x1,y1 = start.x(), start.y()
            x2,y2 = end.x(), end.y()
            s1 = slope(x1, y1, x2, y2)

            for f in ame_feat:
                geom_velo = f.geometry()
                test = geometry.touches(geom_velo)
                if test: # Touche un tronçon aménagé
                    line = geom_velo.asMultiPolyline()[0] if geom_velo.isMultipart() else geom_velo.asPolyline()
                    start2, end2 = line[0], line[-1]
                    x1b,y1b = start2.x(), start2.y()
                    x2b,y2b = end2.x(), end2.y()
                    s2 = slope(x1b, y1b, x2b, y2b)
                    agl = angle(s1, s2)
                    if agl >= 135: # On considère que ce n'est pas une intersection
                        voisins.append(f)
            if len(voisins)>1:
                trou.append(feat)

        

        # On crée un 'id' car l'algo extraxtspecificvertices efface les fid
        sans_ame_id = sans_ame.materialize(QgsFeatureRequest())  # copie
        sans_ame_id.startEditing()
        sans_ame_id.addAttribute(QgsField('seg_id', QVariant.Int))
        sans_ame_id.updateFields()
        idx = sans_ame_id.fields().indexOf('seg_id')
        for f in sans_ame_id.getFeatures():
            sans_ame_id.changeAttributeValue(f.id(), idx, f.id())
        sans_ame_id.commitChanges()
        
        print("Nb entités sans aménagements:", sans_ame_id.featureCount())

        extremites = processing.run(
        "native:extractspecificvertices",
        {'INPUT': sans_ame_id,
         'VERTICES': '0,-1',
         'OUTPUT': 'memory:'})['OUTPUT']
        print("Nb entités extrémités:", extremites.featureCount())
        #Jointure
        join = processing.run(
        "native:joinbynearest",
        {'INPUT': extremites,
         'INPUT_2': velo_lines,
         'FIELDS_TO_COPY': ['comp'],
         'DISCARD_NONMATCHING': False,
         'PREFIX': 'velo_',
         'NEIGHBORS': 1,
         'MAX_DISTANCE': 70,
         'OUTPUT': 'memory:'}
        , context=context, feedback=feedback)['OUTPUT']
        #Plutôt qu'une jointure peut être trouver là où touche les bouts
        
        clusters_par_segment = defaultdict(dict)  # {feature_id: {vertex_index: cluster}}
        idx = join.fields().indexOf('velo_comp')
        print(f"Index des compo : {idx}")
        
        idx = join.fields().indexOf('vertex_index')
        print(f"Index des vertex : {idx}")

        for f in join.getFeatures():
            fid_origine = f['seg_id']   
            vidx = f['vertex_index']
            cluster = f['velo_comp']
            clusters_par_segment[fid_origine][vidx] = cluster
        print(len(clusters_par_segment))
        
        nb_deux_extremites = sum(
            1 for d in clusters_par_segment.values()
            if d.get(0) is not None and d.get(-1) is not None
        )
        nb_une_seule = sum(
            1 for d in clusters_par_segment.values()
            if (d.get(0) is None) != (d.get(-1) is None)
        )
        nb_meme_comp = sum(
            1 for d in clusters_par_segment.values()
            if d.get(0) is not None and d.get(-1) is not None and d.get(0) == d.get(-1)
        )
        feedback.pushInfo(
            f"Tronçons avec les 2 extrémités jointes à un aménagement : {nb_deux_extremites}\n"
            f"Tronçons avec une seule extrémité jointe (l'autre trop loin ou hors seuil) : {nb_une_seule}\n"
            f"Tronçons dont les 2 extrémités tombent dans la MÊME composante : {nb_meme_comp}"
        )
        if nb_deux_extremites == 0:
            feedback.pushWarning(
                "Aucun tronçon n'a ses 2 extrémités à moins de MAX_DISTANCE "
                "d'un aménagement existant : le seuil est probablement trop "
                "petit (ou dans la mauvaise unité, cf. avertissement CRS "
                "plus haut) par rapport aux trous réels du réseau."
            )
        elif nb_deux_extremites == nb_meme_comp:
            feedback.pushWarning(
                "Toutes les extrémités jointes tombent dans la même "
                "composante connexe : soit le réseau cyclable n'a en réalité "
                "qu'une seule composante (vérifiez comp_values ci-dessus), "
                "soit les vrais chaînons manquants nécessitent plusieurs "
                "tronçons consécutifs (pas un seul segment direct) et ne "
                "peuvent donc pas être détectés par cette méthode."
            )


        candidats_ids = []
        for fid, d in clusters_par_segment.items():
            c0 = d.get(0)
            c1 = d.get(-1)
            if c0 is not None and c1 is not None and c0 != c1:
                candidats_ids.append(fid)
        print(len(candidats_ids))
        expr_candidats = f'"seg_id" IN ({",".join(map(str, candidats_ids))})'  # adapter le nom du champ ID
        request_candidats = QgsFeatureRequest().setFilterExpression(expr_candidats)
        chainons_manquants = sans_ame_id.materialize(request_candidats)
        
        
        
        #new_layer = chainons_manquants.materialize(QgsFeatureRequest().setFilterFids(chainons_manquants.allFeatureIds()))
        print("Nb entités:", chainons_manquants.featureCount())
        
        
        if chainons_manquants.featureCount() == 0:
            print("Pas de features !")
            feedback.pushWarning(
                "Aucun chaînon manquant détecté : génération d'un raster "
                "vide (valeur 0 partout) sur l'emprise du réseau "
            )
            
            raster = processing.run("gdal:rasterize", 
                       {'INPUT': reseau,
                        'FIELD':'',
                        'BURN':0,
                        'USE_Z':False,
                        'UNITS':1,
                        'WIDTH':10,'HEIGHT':10,
                        'EXTENT':None,'NODATA':0,
                        'CREATION_OPTIONS':None,
                        'DATA_TYPE':5,'INIT':None,
                        'INVERT':False,'EXTRA':'',
                        'OUTPUT': QgsProcessingUtils.generateTempFilename(
                            'score_services_rasterized.tif', context)}
                       , context=context, feedback=feedback)['OUTPUT']
        else:
            raster = processing.run("gdal:rasterize", 
                   {'INPUT': chainons_manquants,
                    'FIELD':'',
                    'BURN':0,
                    'USE_Z':False,
                    'UNITS':1,
                    'WIDTH':10,'HEIGHT':10,
                    'EXTENT':None,'NODATA':0,
                    'CREATION_OPTIONS':None,
                    'DATA_TYPE':5,'INIT':None,
                    'INVERT':False,'EXTRA':'',
                    'OUTPUT': QgsProcessingUtils.generateTempFilename(
                        'score_services_rasterized.tif', context)}
                   , context=context, feedback=feedback)['OUTPUT']
        print("Chemin raster:", repr(raster))
        import os
        print("Existe:", os.path.exists(raster))
        rlayer = QgsRasterLayer(raster, "Rasterisé")
        formula = f'("{rlayer}@1"- MIN ( "{rlayer}@1"))/ ( MAX ( "{rlayer}@1") - MIN ( "{rlayer}@1"))'
        result = processing.run("native:rastercalc", 
                       {'LAYERS':[rlayer],
                        'EXPRESSION':formula,
                        'EXTENT':None,
                        'CELL_SIZE':None,
                        'CRS':None,
                        'CREATION_OPTIONS':None,
                        'OUTPUT':parameters[self.OUTPUT]})
        processing.run("native:rastercalc", 
                       {'LAYERS':['D:/TFE/donnees/donnees_creees/MNT_proj.tif'],'EXPRESSION':' MIN ( "MNT_proj@1") -  MAX ( "MNT_proj@1")','EXTENT':None,'CELL_SIZE':None,'CRS':None,'CREATION_OPTIONS':None,'OUTPUT':'TEMPORARY_OUTPUT'})
        ds = gdal.Open(raster) if isinstance(raster, str) else raster
        if ds is None:
            raise RuntimeError(f"Impossible d'ouvrir le raster généré : {raster}")

        arr = ds.GetRasterBand(1).ReadAsArray().astype(float)
        r_min = float(np.nanmin(arr))
        r_max = float(np.nanmax(arr))
        feedback.pushInfo(f"score_services min={r_min}, max={r_max}")
        if r_max == r_min:
            feedback.pushWarning("Toutes les valeurs sont identiques, la normalisation est ignorée.")
            formula = "A*0"  # ou une autre valeur par défaut
        else:
            formula = f"((A - {r_min}) / ({r_max} - {r_min})) * 100"

        calcul = processing.run("gdal:rastercalculator", 
                       {'INPUT_A':raster,
                        'BAND_A':1,
                        'INPUT_B':None,'BAND_B':None,
                        'INPUT_C':None,'BAND_C':None,
                        'INPUT_D':None,'BAND_D':None,
                        'INPUT_E':None,'BAND_E':None,
                        'INPUT_F':None,'BAND_F':None,
                        'FORMULA':formula,
                        'NO_DATA':None,
                        'EXTENT_OPT':0,'PROJWIN':None,
                        'RTYPE':5,'CREATION_OPTIONS':None,
                        'EXTRA':'',
                        'OUTPUT':parameters[self.OUTPUT]}
                       , context=context, feedback=feedback)

        return {self.OUTPUT: calcul['OUTPUT']}
    
