"""
/***************************************************************************
 CyclingFacilities
                                 A QGIS plugin
 Ce plugin détermine où faire des aménagements cyclables 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-08-12
        copyright            : (C) 2026 by Eleonore Lagourgue
        email                : elagourgue@free.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Eleonore Lagourgue'
__date__ = '2026-08-12'
__copyright__ = '(C) 2026 by Eleonore Lagourgue'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterString,
                       QgsProcessingParameterEnum, 
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterFile,
                       QgsFeature,
                       QgsWkbTypes,
                       QgsGeometry,
                       QgsFields,
                       QgsField)

from qgis.analysis import (
    QgsVectorLayerDirector,
    QgsNetworkDistanceStrategy,
    QgsNetworkSpeedStrategy,
    QgsGraphBuilder,
    QgsGraphAnalyzer
)
from qgis import processing
from cycling_facilities.conversions import ( 
                         gdf_geom_to_qgs_wkbtype,
                         gdf_to_qgsfields,
                         write_gdf_to_sink,
                         gdf_from_layer_arrow)

from collections import OrderedDict, defaultdict
from scipy.spatial import cKDTree
import pandas as pd



class TripGeneration(QgsProcessingAlgorithm):
    """
    Algorithme pour générer des trajets
    Soit pour le travail soit pour les services
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    POP = 'POP'
    COLPOP = 'COLPOP'
    IDPOP = 'IDPOP'
    
    RESEAU = 'RESEAU'
    ACCIDENTS = "ACCIDENTS"
    VITESSE = 'VITESSE'
    OD_MATRIX = 'OD_MATRIX'
    ORIGINE = "ORIGINE"
    DESTINATION = "DESTINATION"
    COMPTEUR = 'COMPTEUR'
    
    SERVICES = 'SERVICES'
    IDSERV = 'IDSERV'
    CATE='CATE'
    
    DIRECTION_FIELD = 'DIRECTION_FIELD'
    VALUE_FORWARD = 'VALUE_FORWARD'
    VALUE_BACKWARD = 'VALUE_BACKWARD'
    VALUE_BOTH = 'VALUE_BOTH'
    DEFAULT_DIRECTION = 'DEFAULT_DIRECTION'
    SPEED_FIELD = 'SPEED_FIELD'
    DEFAULT_SPEED = 'DEFAULT_SPEED'
    TOLERANCE = 'TOLERANCE'


    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Génération de trajets'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Traitements'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return TripGeneration()
    
    
    def initAlgorithm(self, config):
        
        self.DIRECTIONS = OrderedDict([
        ('Forward direction', QgsVectorLayerDirector.DirectionForward),
        ('Backward direction', QgsVectorLayerDirector.DirectionBackward),
        ('Both directions', QgsVectorLayerDirector.DirectionBoth)])
        
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.POP,
                self.tr('Couche de population (point)'),
                [QgsProcessing.SourceType.TypeVectorPoint]
            )
        )
        self.addParameter(
            QgsProcessingParameterField(self.IDPOP, 
                                                      "Colonne id pour la couche de population",
                                                      parentLayerParameterName=self.POP))
        self.addParameter(
            QgsProcessingParameterField(self.COLPOP, 
                                                      "Colonne population pour la couche de population",
                                                      parentLayerParameterName=self.POP,
                                                      optional = True))
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.RESEAU,
                self.tr('Réseau'),
                [QgsProcessing.SourceType.TypeVectorLine]
            )
        )
        self.addParameter(QgsProcessingParameterField(self.DIRECTION_FIELD, 
                                                      self.tr("Colonne direction"),
                                                      parentLayerParameterName=self.RESEAU,
                                                      optional= True))
        self.addParameter(QgsProcessingParameterString(self.VALUE_FORWARD, 
                                                       self.tr("Sens direct (à remplir si la colonne de direction est renseignée)"),
                                                       optional=True,
                                                       defaultValue=None))
        self.addParameter(QgsProcessingParameterString(self.VALUE_BACKWARD, 
                                                       self.tr("Sens inverse (à remplir si la colonne de direction est renseignée)"),
                                                       optional = True,
                                                       defaultValue=None))
        self.addParameter(QgsProcessingParameterString(self.VALUE_BOTH, 
                                                       self.tr("Double sens (à remplir si la colonne de direction est renseignée)"),
                                                       optional=True,
                                                       defaultValue=None))
        self.addParameter(QgsProcessingParameterEnum(self.DEFAULT_DIRECTION,
                                                 self.tr("Direction par défaut"),
                                                 list(self.DIRECTIONS.keys()),
                                                 optional = True,
                                                 defaultValue=None))
        self.addParameter(QgsProcessingParameterField(self.SPEED_FIELD, 
                                                      self.tr("Colonne vitesse"), 
                                                      parentLayerParameterName=self.RESEAU,
                                                      optional=True))
        self.addParameter(QgsProcessingParameterString(self.DEFAULT_SPEED, self.tr("Vitesse par défaut"), defaultValue=50))
        
        #Destinations
        self.addParameter(QgsProcessingParameterFile(self.OD_MATRIX, "Matrice OD",
                                                     optional = True))

        self.addParameter(QgsProcessingParameterString(self.ORIGINE, 
                                                       "Colonne origine (obligatoire si matrice OD)",
                                                       optional = True))
        self.addParameter(QgsProcessingParameterString(self.DESTINATION, 
                                                      "Colonne destination(obligatoire si matrice OD)",
                                                      optional = True))
        self.addParameter(QgsProcessingParameterString(self.COMPTEUR, 
                                                      "Colonne renseignant le volume de flux entre origine et destination (obligatoire si matrice OD)",
                                                      optional = True))
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.SERVICES,
                self.tr('Couche de services (point)'),
                [QgsProcessing.SourceType.TypeVectorPoint],
                optional = True
            )
        )                  
        self.addParameter(
            QgsProcessingParameterField(self.IDSERV, 
                                               "Colonne id pour la couche de services",
                                               parentLayerParameterName=self.SERVICES,
                                               optional = True))
        self.addParameter(
            QgsProcessingParameterField(self.CATE, 
                                               "Colonne catégories des services (si existe), \n Ex: Santé, Education...",
                                               parentLayerParameterName=self.SERVICES,
                                               optional = True))                       
        self.addParameter(
            QgsProcessingParameterNumber(
                self.TOLERANCE, 
                self.tr("Tolérance topologique (en mètres)"), defaultValue=0.0))
        
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )
    
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        pop = self.parameterAsSource(parameters, self.POP, context)
        id_pop = self.parameterAsString(parameters, self.IDPOP,context)

        reseau = self.parameterAsVectorLayer(parameters, self.RESEAU, context)
        tolerance = self.parameterAsDouble(parameters, self.TOLERANCE, context)
        colonne_direction = self.parameterAsString(parameters, self.DIRECTION_FIELD, context)
        value_forward = self.parameterAsString(parameters, self.VALUE_FORWARD, context)
        value_backward = self.parameterAsString(parameters, self.VALUE_BACKWARD, context)
        value_both = self.parameterAsString(parameters, self.VALUE_BOTH, context)
        default_direction = self.parameterAsString(parameters, self.DEFAULT_DIRECTION, context)
        
        od_matrix = self.parameterAsFile(parameters, self.OD_MATRIX, context)
        origine = self.parameterAsString(parameters, self.ORIGINE, context)
        dest = self.parameterAsString(parameters, self.DESTINATION, context)
        cpt = self.parameterAsString(parameters, self.COMPTEUR, context)

        services = self.parameterAsSource(parameters, self.SERVICES, context)#QgsProcessingFeatureSource
        pop_column = self.parameterAsString(parameters, self.COLPOP,context)
        id_service = self.parameterAsString(parameters, self.IDSERV,context)

        if (services is None and pop_column ) or (services is not None and not pop_column ):
            feedback.pushWarning(" Erreur : il manque une des deux informations \n Colonne population ou couche de services")
            exit()
        
        
        
        
        test_liste = [od_matrix, origine, dest, cpt]
        res = [i for i in range(len(test_liste)) if test_liste[i] == None or not test_liste[i]]

        if 0<len(res)<4:
            feedback.pushWarning(" Erreur : il manque une des quatre informations \n Matrice OD, Colonne deestination/origine/compteur")
            exit()
        
        idx_key = reseau.fields().indexOf(colonne_direction)
        director = QgsVectorLayerDirector(
            reseau,
            idx_key,        # index du champ de direction (-1 si pas de sens unique)
            value_forward,        # valeur "sens direct"
            value_backward,        # valeur "sens inverse"
            value_both,        # valeur "double sens"
            QgsVectorLayerDirector.DirectionBoth  # direction par défaut
        )
        strategy = QgsNetworkDistanceStrategy()
        director.addStrategy(strategy)
        crs = reseau.crs()
        builder = QgsGraphBuilder(crs)
        
        
        #my_lyr = QgsVectorLayer('Linestring?crs=epsg:2154', 'network result', 'memory')
        Points_dep = []
        NbPop =[]
        IdPop = []
        for feat in pop.getFeatures():
            geom = feat.geometry().asPoint()
            IdPop.append(feat[id_pop])
            if pop_column:
                nb_pop = feat[pop_column]
                NbPop.append(nb_pop)
            Points_dep.append(geom)
        
        edge_traffic = defaultdict(lambda: {'poids': 0.0, 'p1': None, 'p2': None})
        n_orig = pop.featureCount()

        if services is not None:
            feedback.pushInfo("Méthode déplacements vers services")

            Points_arr =[]
            for feat in services.getFeatures():
                geom = feat.geometry().asPoint()
                Points_arr.append(geom)
            
            Points = Points_dep +Points_arr
            tiedPoints = director.makeGraph(builder, Points) 
            graph = builder.graph()
            
            # result = processing.run("qgis:distancematrix", {
            #     'INPUT': pop,'INPUT_FIELD':'AXE',
            #     'TARGET':services,'TARGET_FIELD':'id',
            #     'MATRIX_TYPE':0,'NEAREST_POINTS':1,
            #     'OUTPUT':'TEMPORARY_OUTPUT'})['OUTPUT']
            
            vertex_origines = [graph.findVertex(tiedPoints[i]) for i in range(n_orig)]
            vertex_destinations = [graph.findVertex(tiedPoints[n_orig + j]) for j in range((services.featureCount()))]
            assignations = []
            
            for i, v_orig in enumerate(vertex_origines):
                if feedback.isCanceled():
                            break
                (tree, cost) = QgsGraphAnalyzer.dijkstra(graph, v_orig, 0)
                best_j, best_v, best_cost = None, None, None
                for j, v_dest in enumerate(vertex_destinations):
                    if v_dest == v_orig:
                        c = 0.0
                    elif tree[v_dest] == -1 and v_dest != v_orig:
                        feedback.pushWarning(f"Pas de chemin entre origine {i} et destination {j}")
                        continue
                    else:
                        c = cost[v_dest]
                    
                    # On compare avec les résultats trouvés avant
                    if best_cost is None or c < best_cost:
                        best_cost, best_j, best_v = c, j, v_dest
                    if best_j is None:
                        feedback.pushWarning(f"Commune {i} : aucun service atteignable")
                        continue
                    assignations.append({
                        'commune_idx': i,
                        'service_idx': best_j,
                        'distance': best_cost
                    })
                    # Reconstruction du chemin en remontant les arêtes depuis la destination
                    current = best_v
                    while current != v_orig:
                        edge_id = tree[current]
                        if edge_id == -1:
                            break
                        key, p1, p2 = self.edge_key(graph, edge_id)
                        edge_traffic[key]['poids'] += NbPop[i]
                        edge_traffic[key]['p1'] = p1
                        edge_traffic[key]['p2'] = p2
                        current = graph.edge(edge_id).fromVertex()
                        
        
                    
        
                    
        elif od_matrix is not None:
            feedback.pushInfo("Méthode déplacements vers travail")

            tiedPoints = director.makeGraph(builder, Points_dep) 
            graph = builder.graph()
            
            
            df_matrix = pd.read_csv(od_matrix, sep = None, engine = 'python')
            vertex_origines = [graph.findVertex(tiedPoints[i]) for i in range(n_orig)]
            for i, v_orig in enumerate(vertex_origines):
                if feedback.isCanceled():
                            break
                (tree, cost) = QgsGraphAnalyzer.dijkstra(graph, v_orig, 0)
                id_ori = IdPop[i]
                od = df_matrix[df_matrix[origine] == id_ori]
                for j , v_dest in enumerate(vertex_origines):
                    if i != j:
                        if tree[v_dest] == -1 and v_dest != v_orig:
                            feedback.pushWarning(f"Pas de chemin entre origine {i} et destination {j}")
                            continue
                        if j in od[dest].values:
                            pop = od[cpt][od[dest] == j]
                            
                            od_velo = pop * 3/100 # Part du vélo à environ 3% dans les trajets domicile-travail
                            current = v_dest
                            while current != v_orig:
                                edge_id = tree[current]
                                if edge_id == -1:
                                    break
                                key, p1, p2 = self.edge_key(graph, edge_id)
                                edge_traffic[key]['poids'] += od_velo
                                edge_traffic[key]['p1'] = p1
                                edge_traffic[key]['p2'] = p2
                                current = graph.edge(edge_id).fromVertex()
                        else:
                            feedback.pushInfo("Pas de trajet déclaré")
                            continue

                            
            
                        
        feedback.pushInfo("Ecriture dans le sink")
        fields_traffic = QgsFields()
        fields_traffic.append(QgsField('trafic', QVariant.Double))
        (sink_traffic, dest_id) = self.parameterAsSink(
        parameters, self.OUTPUT, context,
        fields_traffic, QgsWkbTypes.LineString, reseau.crs()
        )
        for key, data in edge_traffic.items():
            geom = QgsGeometry.fromPolylineXY([data['p1'], data['p2']])
            feat = QgsFeature(fields_traffic)
            feat.setGeometry(geom)
            feat.setAttributes([data['poids']])
            sink_traffic.addFeature(feat, QgsFeatureSink.FastInsert)
        return {self.OUTPUT: dest_id}
    
    
    def edge_key(self, graph, edge_id, precision=6):
        """Clé indépendante du sens de parcours, pour fusionner aller/retour."""
        edge = graph.edge(edge_id)
        p1 = graph.vertex(edge.fromVertex()).point()
        p2 = graph.vertex(edge.toVertex()).point()
        k1 = (round(p1.x(), precision), round(p1.y(), precision))
        k2 = (round(p2.x(), precision), round(p2.y(), precision))
        return tuple(sorted([k1, k2])), p1, p2
    